onaio/fhir-web

packages/keycloak-service/src/service/errors.ts
packages/keycloak-service/src/service/serviceClass.ts
packages/keycloak-user-management/src/components/Credentials/index.tsx
packages/keycloak-user-management/src/components/Loading/index.tsx
packages/keycloak-user-management/src/components/index.tsx
packages/keycloak-user-management/src/forms/index.tsx
packages/opensrp-store/src/store/ducks/index.ts

This PR addresses to #77
close #77

add jsDocs for existing functions

---

package.json
packages/keycloak-service/dist/types/service/errors.d.ts
packages/keycloak-service/dist/types/service/serviceClass.d.ts
packages/keycloak-user-management/dist/components/CreateEditUser/index.js
packages/keycloak-user-management/dist/components/Credentials/index.js
packages/keycloak-user-management/dist/components/index.js
packages/keycloak-user-management/dist/constants.js
packages/keycloak-user-management/dist/forms/index.js
packages/keycloak-user-management/dist/types/components/CreateEditUser/index.d.ts
packages/keycloak-user-management/dist/types/components/Credentials/index.d.ts
packages/keycloak-user-management/dist/types/components/Loading/index.d.ts
packages/keycloak-user-management/dist/types/components/index.d.ts
packages/keycloak-user-management/dist/types/constants.d.ts
packages/keycloak-user-management/dist/types/forms/index.d.ts
packages/opensrp-store/dist/types/store/ducks/index.d.ts
packages/opensrp-store/dist/types/store/selectors.d.ts

Update distribution files for packages **keycloak-service**, **keycloak-user-management** , **opensrp-store**

Transpile packages

---

packages/keycloak-service/package.json
packages/location-management/package.json
packages/opensrp-reducer-factory/package.json
packages/opensrp-server-service/package.json
packages/opensrp-store/package.json

babel command with apostrophe around extensions leads to 0 transpilled files on windows Os. This PR will just add extra transpilation command to compile packages on windows OS

Add transpilation command afor windows OS

---

packages/keycloak-user-management/src/components/UserList/TableActions/index.tsx
packages/keycloak-user-management/src/components/UserList/TableActions/tests/index.test.tsx
packages/keycloak-user-management/src/components/UserList/index.tsx
packages/keycloak-user-management/src/components/UserList/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/UserList/tests/index.test.tsx
packages/keycloak-user-management/src/components/UserList/utils.tsx

117 prevent deleting logged in account

---

packages/location-management/src/components/LocationUnitAdd/Form.tsx

Fix geographicLevel always 0 Bug

---

client/.env.sample
client/package.json
client/src/App/App.tsx
client/src/App/utils.tsx
client/src/components/page/Sidebar/index.tsx
client/src/configs/__mocks__/env.ts
client/src/configs/env.ts
client/src/constants.tsx
client/src/containers/ConnectedSidebar/tests/__snapshots__/index.test.tsx.snap
client/yarn.lock
docs/env.md
packages/product-catalogue/package.json
yarn.lock

let package = product-catalogue
- publish package
- Add menu item in client to package
- Register routes for components in App.

Hook up product catalogue to client

---

packages/opensrp-server-service/package.json
packages/opensrp-server-service/src/serviceClass.ts
packages/opensrp-server-service/src/tests/index.test.ts
yarn.lock

for Post and Put requests:
- before:
- the body could only have been application/json
- now:
- the body can be structured in anyway, i.e. using arbitrary MIME types
This is a backwards compatible change

Allow to user to structure the body in post and put

---

.eslintignore
.eslintrc.js
client/yarn.lock
package.json
packages/keycloak-service/src/service/serviceClass.ts
packages/keycloak-user-management/src/components/CreateEditUser/index.tsx
packages/keycloak-user-management/src/components/UserList/TableActions/index.tsx
packages/keycloak-user-management/src/components/UserList/index.tsx
packages/keycloak-user-management/src/components/UserList/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/UserList/tests/index.test.tsx
packages/keycloak-user-management/src/components/UserList/utils.tsx
packages/keycloak-user-management/src/constants.tsx
packages/opensrp-reducer-factory/src/index.ts
packages/opensrp-server-service/src/serviceClass.ts
packages/opensrp-store/src/store/selectors.ts
packages/opensrp-store/src/store/store.ts
packages/opensrp-store/src/store/tests/ducks/messages.ts
packages/product-catalogue/src/components/ProductForm/index.tsx
yarn.lock

fix: #57 
Pr has tested https://github.com/OpenSRP/web/pull/56 and works fine
The pr updates typescript to version 3.8.3 and fixes unnecessary conditionals
Fix unending loader in the event of an error from API

Ensure js files are linted too

---

client/src/App/App.css
client/src/components/page/Header/Header.css
client/src/components/page/Header/index.tsx
client/src/components/page/Sidebar/Sidebar.css
client/src/components/page/Sidebar/index.tsx
client/src/containers/ConnectedHeader/tests/__snapshots__/index.test.tsx.snap
client/src/containers/ConnectedSidebar/tests/__snapshots__/index.test.tsx.snap
client/src/containers/pages/Home/Home.css
client/src/containers/pages/Home/Home.tsx
client/src/containers/pages/Home/tests/__snapshots__/Home.test.tsx.snap
packages/keycloak-user-management/src/components/Credentials/index.tsx
packages/keycloak-user-management/src/components/Credentials/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/UserList/index.tsx
packages/keycloak-user-management/src/components/forms/UserForm/index.tsx
packages/keycloak-user-management/src/index.css

Remove antd overidden styles

---

packages/keycloak-user-management/package.json

keyclock user management module was missing scripts so i just updated/added them into packages

Update Scripts in keyclock user management module

---

client/src/containers/ConnectedSidebar/tests/__snapshots__/index.test.tsx.snap
packages/product-catalogue/package.json
packages/product-catalogue/src/components/CreateProduct/index.tsx
packages/product-catalogue/src/components/CreateProduct/tests/__snapshots__/index.test.tsx.snap
packages/product-catalogue/src/components/CreateProduct/tests/index.test.tsx
packages/product-catalogue/src/components/EditProduct/index.tsx
packages/product-catalogue/src/components/EditProduct/tests/__snapshots__/index.test.tsx.snap
packages/product-catalogue/src/components/ListView/index.tsx
packages/product-catalogue/src/components/ListView/tests/index.test.tsx
packages/product-catalogue/src/components/ListView/utils.tsx
packages/product-catalogue/src/components/ProductForm/index.tsx
packages/product-catalogue/src/components/ProductForm/tests/__snapshots__/index.test.tsx.snap
packages/product-catalogue/src/components/ProductForm/tests/fixtures.tsx
packages/product-catalogue/src/components/ProductForm/tests/index.test.tsx
packages/product-catalogue/src/components/ViewDetails/index.tsx
packages/product-catalogue/src/components/ViewDetails/tests/__snapshots__/index.test.tsx.snap
packages/product-catalogue/src/components/ViewDetails/tests/index.test.tsx
packages/product-catalogue/src/constants.ts
packages/product-catalogue/src/ducks/productCatalogue/index.ts
packages/product-catalogue/src/ducks/productCatalogue/tests/fixtures.ts
packages/product-catalogue/src/helpers/dataLoaders.ts
packages/product-catalogue/src/helpers/tests/dataLoaders.test.tsx
packages/product-catalogue/src/index.css
packages/product-catalogue/src/lang.ts
yarn.lock

- Get token in calleable function so that we prevent dealing with stale tokens.
- Refactor routes so that they do not collide
- Refactor post and put payloads, Change how the payload is structured.
- Resolve UI feedback here: #94
close #93 close #94 close #96

93 catalgoue fix

---

client/.env.sample
client/src/App/App.tsx
client/src/App/utils.tsx
client/src/components/page/Sidebar/index.tsx
client/src/configs/env.ts
client/src/constants.tsx
docs/env.md
packages/opensrp-plans/package.json
packages/opensrp-plans/src/components/ListView/index.tsx
packages/opensrp-plans/src/components/ListView/tests/__snapshots__/index.test.tsx.snap
packages/opensrp-plans/src/components/ListView/tests/index.test.tsx
packages/opensrp-plans/src/components/ListView/utils.tsx
packages/opensrp-plans/src/constants.tsx
packages/opensrp-plans/src/ducks/index.ts
packages/opensrp-plans/src/ducks/tests/fixtures.ts
packages/opensrp-plans/src/helpers/common.ts
packages/opensrp-plans/src/helpers/dataLoaders.ts
packages/opensrp-plans/src/helpers/tests/dataLoaders.test.tsx
packages/opensrp-plans/src/index.tsx
packages/opensrp-plans/src/lang.ts
yarn.lock

fix: #165 
Pr Adds missions/plans list view
Should  fix :
https://github.com/OpenSRP/web/issues/211

165 plans list UI

---

packages/opensrp-plans/src/components/NewPlan/index.tsx
packages/opensrp-plans/src/components/NewPlan/tests/index.test.tsx
packages/plan-form/src/helpers/types.ts
packages/plan-form/src/helpers/utils.tsx

Remove initial date Range values during plan creation

Remove initial date Range values during plan creation

---

packages/product-catalogue/src/components/ListView/index.tsx
packages/product-catalogue/src/components/ListView/tests/index.test.tsx
packages/product-catalogue/src/lang.ts

Change add product catalogue button text

Change add product catalogue button text

---

packages/plan-form-core/src/formHelpers/activitiesLookup.ts
packages/plan-form-core/src/formHelpers/constants/lang.ts
packages/plan-form/src/Form/tests/__snapshots__/index.test.tsx.snap
packages/plan-form/src/Form/tests/fixtures.tsx

The pr aims to: Update plan activities to match the finalized plan definition
The pr should be merged once we have clarity on this issue
https://github.com/OpenSRP/web/issues/180#issuecomment-744284497
Fix: #227

Update planactivities template

---

packages/keycloak-user-management/src/components/forms/UserForm/tests/utils.test.tsx
packages/keycloak-user-management/src/components/forms/UserForm/utils.tsx

Redirect user to credentials after creation

---

packages/team-management/src/components/TeamsView/Table.tsx
packages/team-management/src/components/TeamsView/tests/table.test.tsx

add pagination in teams view table

---

client/src/App/App.tsx
client/src/App/utils.tsx
packages/opensrp-plans/README.md
packages/opensrp-plans/src/components/ActivateMission/index.tsx
packages/opensrp-plans/src/components/ActivateMission/tests/index.test.tsx
packages/opensrp-plans/src/components/PlanInfo/index.tsx
packages/opensrp-plans/src/components/PlanInfo/tests/__snapshots__/index.test.tsx.snap
packages/opensrp-plans/src/components/PlanInfo/tests/index.test.tsx
packages/opensrp-plans/src/constants.tsx
packages/opensrp-plans/src/containers/ListView/utils.tsx
packages/opensrp-plans/src/containers/PlanAssignment/index.tsx
packages/opensrp-plans/src/containers/PlanAssignment/tests/index.test.tsx
packages/opensrp-plans/src/index.css
packages/opensrp-plans/src/lang.ts

close #253 
adds a card with button to activate a draft plan,
Fix routes in plan assignment profile breadcrumb routes

Activate mission

---

packages/team-assignment/src/components/ListView/index.tsx

Add pagination in teams assignment table

---

packages/keycloak-user-management/src/components/forms/UserForm/index.tsx
packages/keycloak-user-management/src/components/forms/UserForm/tests/index.test.tsx

Practitioner toggle issue

---

packages/react-utils/package.json
packages/react-utils/src/helpers/dataLoaders.ts
packages/react-utils/src/helpers/tests/dataLoaders.test.ts

222 add generic opensrp service class

---

packages/team-management/src/components/TeamsAddEdit/index.tsx
packages/team-management/src/components/TeamsAddEdit/tests/fixtures.ts
packages/team-management/src/components/TeamsAddEdit/tests/index.test.tsx

add team name in header on edit

---

packages/location-management/src/components/LocationUnitAddEdit/Form.tsx
packages/location-management/src/components/LocationUnitAddEdit/index.tsx
packages/location-management/src/components/LocationUnitAddEdit/tests/index.test.tsx
packages/location-management/src/components/LocationUnitView/index.tsx

Select the parent location automatically during location unit creation

---

packages/opensrp-plans/src/components/MissionData/index.tsx
packages/opensrp-plans/src/components/MissionData/tests/index.test.tsx
packages/opensrp-plans/src/constants.ts
packages/opensrp-plans/src/containers/PlanAssignment/index.tsx
packages/opensrp-plans/src/ducks/planDefinitions/tests/fixtures.ts
packages/opensrp-plans/src/helpers/tests/utils.test.tsx
packages/opensrp-plans/src/helpers/utils.tsx

This pr adds
Mission Data export functionality
the zip file is exported once we hit the export data API as described here https://github.com/OpenSRP/opensrp-server-web/issues/637#issuecomment-763582646 
Fix: #275

Add export functionality

---

packages/keycloak-user-management/src/components/forms/UserForm/index.tsx
packages/keycloak-user-management/src/components/forms/UserForm/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/forms/UserForm/tests/index.test.tsx

Practitioner toggle 371

---

packages/inventory/src/ducks/inventory.ts
packages/inventory/src/ducks/tests/inventory.test.ts

405 reselect

---

packages/location-management/src/components/LocationUnitAddEdit/Form.tsx
packages/location-management/src/components/LocationUnitAddEdit/tests/Form.test.tsx
packages/location-management/src/components/LocationUnitAddEdit/tests/fixtures.ts

Fix geolocation 0 bug

---

packages/inventory/src/ducks/inventory.ts
packages/inventory/src/ducks/tests/fixtures.ts
packages/inventory/src/ducks/tests/inventory.test.ts

add inventory ducks

---

packages/inventory/src/constants.ts
packages/inventory/src/containers/ListView/index.tsx
packages/inventory/src/containers/ListView/tests/__snapshots__/index.test.tsx.snap
packages/inventory/src/containers/ListView/tests/fixtures.ts
packages/inventory/src/containers/ListView/tests/index.test.tsx
packages/inventory/src/helpers/dataLoaders.ts

pull all locations
Add a call to get the count of structures,
use the reponse to set the limit on the number of structures to return

Pull all structures

---

packages/location-management/src/components/LocationForm/tests/fixtures.ts
packages/location-management/src/components/LocationForm/tests/index.test.tsx
packages/location-management/src/constants.ts

close #430 
Refactor service types setting id value

Fix service type settings api call identifier

---

packages/team-management/src/components/TeamsAddEdit/Form.tsx
packages/team-management/src/components/TeamsView/Table.tsx

This PR addresses #383 and #385

Clean team management package

---

packages/location-management/src/components/LocationTree/index.tsx
packages/location-management/src/ducks/locationHierarchy/utils.tsx

- Fixes locations duplicating on expanding/collapsing tree
- Fixes tree search bug

414 location tree bug fixes

---

app/src/App/App.css
app/src/App/App.tsx
app/src/components/page/Sidebar/index.tsx
app/src/containers/ConnectedSidebar/tests/__snapshots__/index.test.tsx.snap
app/src/lang.ts

Hook up bulk upload to routes

---

packages/location-management/src/components/LocationForm/ExtraFields/index.tsx
packages/location-management/src/components/LocationForm/index.tsx
packages/location-management/src/components/LocationForm/tests/__snapshots__/index.test.tsx.snap
packages/location-management/src/components/LocationForm/tests/fixtures.ts
packages/location-management/src/components/LocationForm/tests/index.test.tsx
packages/location-management/src/components/LocationForm/utils.tsx
packages/location-management/src/ducks/location-units.ts

- correct schema for expected servicetype setting payload
- fix schema for posted location unit; related to #326

Data schema correction

---

packages/react-utils/src/components/Search/index.tsx
packages/react-utils/src/components/Search/tests/index.test.tsx

close #439 
Make search clearable

Make search clearable

---

packages/inventory/src/components/PostConfirmationSuccess/index.tsx
packages/inventory/src/components/PostConfirmationSuccess/tests/index.test.tsx
packages/inventory/src/containers/BulkUpload/index.tsx
packages/inventory/src/containers/BulkUpload/tests/integration.test.tsx
packages/inventory/src/helpers/dataLoaders.ts
packages/inventory/src/helpers/tests/dataloaders.test.tsx

close #440
Fix how we parse response data to show the number of imported inventory items

Fix bulk upload 

---

packages/opensrp-plans/src/components/MissionData/index.tsx
packages/opensrp-plans/src/components/MissionData/tests/index.test.tsx
packages/opensrp-plans/src/constants.ts
packages/opensrp-plans/src/helpers/dataLoaders.ts

Add business status to mission indicators fetch calls
part of #376

Add business status to mission indicators fetch calls

---

packages/inventory/src/containers/ServicePointProfile/index.tsx

Pass coordinates strings as value

Pass coordinates strings as value

---

packages/inventory/src/components/InventoryList/tests/__snapshots__/index.test.tsx.snap
packages/inventory/src/components/InventoryList/tests/index.test.tsx
packages/inventory/src/containers/ServicePointProfile/index.tsx
packages/inventory/src/containers/ServicePointProfile/tests/__snapshots__/index.test.tsx.snap
packages/inventory/src/containers/ServicePointProfile/tests/index.test.tsx
packages/inventory/src/containers/ServicePointProfile/utils.tsx

Update tests; add a few snapshot test

Update tests; add a few snapshot test

---

packages/plan-form-core/src/formHelpers/activitiesLookup.ts
packages/plan-form-core/src/formHelpers/tests/eusm.fixtures.ts
packages/plan-form-core/src/formHelpers/tests/eusm.test.tsx
packages/plan-form-core/src/formHelpers/types.ts
packages/plan-form/src/Form/tests/__snapshots__/index.test.tsx.snap
packages/plan-form/src/Form/tests/fixtures.tsx
packages/plan-form/src/Form/tests/index.test.tsx

Addresses openSRP/opensrp-server-web#733
Adds a dynamic value to the Product Check titled plan activity

Update productCheck action in plan activities look up

---

packages/inventory/src/containers/ServicePointProfile/index.tsx
packages/inventory/src/containers/ServicePointProfile/tests/__snapshots__/index.test.tsx.snap
packages/inventory/src/containers/ServicePointProfile/tests/index.test.tsx

Dispatch fetched trees to store in service point profile
close #480

Fix Trees action not dispatched to store

---

packages/plan-form-core/src/formHelpers/activitiesLookup.ts
packages/plan-form-core/src/formHelpers/tests/eusm.fixtures.ts
packages/plan-form-core/src/formHelpers/types.ts
packages/plan-form/src/Form/tests/__snapshots__/index.test.tsx.snap
packages/plan-form/src/Form/tests/fixtures.tsx

This pr updates plan activities lookup:
- adds the dynamic prop for the following actions:
- record_gps
- service_point_check
as requested for here closes #501

Update plan actions

---

packages/opensrp-plans/src/components/PlanInfo/index.tsx
packages/opensrp-plans/src/components/PlanInfo/tests/__snapshots__/index.test.tsx.snap
packages/opensrp-plans/src/components/PlanInfo/tests/index.test.tsx
packages/opensrp-plans/src/containers/ListView/utils.tsx
packages/opensrp-plans/src/containers/PlanAssignment/tests/__snapshots__/index.test.tsx.snap
packages/opensrp-plans/src/index.css

Mission QA fixes

---

packages/keycloak-user-management/src/components/CreateEditUserGroup/Form.tsx
packages/keycloak-user-management/src/components/CreateEditUserGroup/index.tsx
packages/keycloak-user-management/src/components/CreateEditUserGroup/tests/Form.test.tsx
packages/keycloak-user-management/src/components/CreateEditUserGroup/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/CreateEditUserGroup/tests/index.test.tsx
packages/keycloak-user-management/src/components/CreateEditUserGroup/tests/utils.test.tsx
packages/keycloak-user-management/src/components/CreateEditUserGroup/utils.tsx
packages/keycloak-user-management/src/components/UserRolesList/index.tsx
packages/keycloak-user-management/src/components/UserRolesList/utils.tsx
packages/keycloak-user-management/src/constants.ts
packages/keycloak-user-management/src/ducks/tests/fixtures.ts
packages/keycloak-user-management/src/index.css
packages/keycloak-user-management/src/lang.ts

- Add ability to assign/unassign roles to user groups
addresses #428

428 assign roles to user groups

---

packages/opensrp-plans/src/components/MissionData/index.tsx
packages/opensrp-plans/src/components/MissionData/tests/index.test.tsx
packages/opensrp-plans/src/constants.ts
packages/opensrp-plans/src/helpers/dataLoaders.ts

Fix the search param that's used when fetching mission idnicators.
close #512

Change status param when fetching mission indicators

---

app/src/App/App.css
packages/inventory/src/constants.ts
packages/inventory/src/containers/ListView/index.tsx
packages/inventory/src/containers/ListView/tests/__snapshots__/index.test.tsx.snap
packages/inventory/src/containers/ListView/tests/index.test.tsx

Service point inventory Design QA fixes

---

packages/form-config/package.json

Publish package `@opensrp/form-config` following merged PR https://github.com/OpenSRP/web/pull/530

Publish @opensrp/form-config

---

packages/keycloak-user-management/src/components/UserList/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/UserList/tests/index.test.tsx
packages/keycloak-user-management/src/components/UserList/utils.tsx

Fix users table sorting bug

---

packages/inventory/src/containers/ListView/index.tsx
packages/inventory/src/containers/ListView/utils.tsx

This PR addresses QA fix for i[ssue #492](https://github.com/OpenSRP/web/issues/492#issuecomment-797331054)

UI fixes for inventory

---

packages/inventory/src/index.css
packages/keycloak-user-management/src/index.css
packages/opensrp-plans/src/containers/ListView/index.tsx
packages/opensrp-plans/src/index.css
packages/product-catalogue/src/components/ListView/index.tsx
packages/product-catalogue/src/index.css
packages/react-utils/src/components/CommonStyles/index.css

Design regression

---

docs/mls.md

Update MLS doc

---

packages/plan-form-core/src/formHelpers/helpers.ts

Fixes #575 
Notes: 
Quirky when using optional chaining with equality check. `object?.property?.someString !== ""` could evaluate to `undefined !== ""` which is true

optional chaining in place of logical AND

---

app/src/components/page/Sidebar/index.tsx
app/src/containers/ConnectedSidebar/tests/index.test.tsx
packages/team-assignment/package.json
yarn.lock

Team Assignment Bug

---

packages/location-management/src/components/LocationUnitList/index.tsx
packages/location-management/src/components/LocationUnitList/tests/__snapshots__/index.test.tsx.snap
packages/location-management/src/components/LocationUnitList/tests/index.test.tsx

render LocationUnit Table only after tableData is evaluated

---

packages/location-management/src/components/LocationForm/utils.tsx

Related to https://github.com/OpenSRP/web/issues/266

Fix the Types to be more specific

---

app/.env.sample
app/src/components/page/CustomCallback/tests/index.test.tsx
app/src/configs/__mocks__/env.ts
app/src/configs/env.ts
app/src/configs/settings.ts
docs/env.md

Refactor to explicitly set OAuth authorization scopes via env vars.

Add env var to set oauth scope

---

packages/keycloak-user-management/src/components/CreateEditUser/tests/index.test.tsx
packages/keycloak-user-management/src/components/UserGroupsList/index.tsx
packages/keycloak-user-management/src/components/UserList/index.tsx
packages/keycloak-user-management/src/components/forms/UserForm/index.tsx
packages/keycloak-user-management/src/components/forms/UserForm/tests/index.test.tsx
packages/keycloak-user-management/src/components/forms/UserForm/tests/utils.test.tsx
packages/keycloak-user-management/src/components/forms/UserForm/utils.tsx

User management Design QA

---

packages/plan-form/src/Form/index.tsx
packages/plan-form/src/Form/tests/__snapshots__/index.test.tsx.snap
packages/plan-form/src/Form/tests/index.test.tsx
packages/plan-form/src/helpers/utils.tsx

576 invalid date error when plan has no end date

---

packages/card-support/src/components/DownloadClientData/tests/index.test.tsx
packages/card-support/src/components/DownloadClientData/tests/utils.test.tsx
packages/card-support/src/constants.ts

Fix card support malformed user assignment URL

---

packages/team-assignment/src/components/ListView/index.tsx
packages/team-assignment/src/components/ListView/tests/index.test.tsx
packages/team-assignment/src/components/ListView/tests/utils.test.tsx
packages/team-assignment/src/components/ListView/utils.tsx

608 fix team unassigning bug

---

app/src/containers/ConnectedSidebar/tests/__snapshots__/index.test.tsx.snap
app/src/routes.test.tsx
app/src/routes.tsx

619 add missing bulk upload menu item on inventory submenu

---

packages/keycloak-user-management/src/components/Credentials/index.tsx
packages/keycloak-user-management/src/components/Credentials/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/Credentials/tests/index.test.tsx
packages/keycloak-user-management/src/components/forms/UserForm/index.tsx
packages/keycloak-user-management/src/components/forms/UserForm/tests/utils.test.tsx
packages/keycloak-user-management/src/components/forms/UserForm/utils.tsx

- Fixes removing users from groups
- Remove temporary password toggle and set temporary field in payload to false
-  Redirect newly created users to credentials page
closes #632

632 user management bug fixes

---

docker/confd_env.toml

Fix missing comma

---

packages/keycloak-user-management/src/components/forms/UserForm/index.tsx
packages/keycloak-user-management/src/components/forms/UserForm/tests/utils.test.tsx
packages/keycloak-user-management/src/components/forms/UserForm/utils.tsx

Fixes error that pops up when creating a new user that hasn't been assigned to a user group
closes #644

644 fix error credentials page

---

packages/keycloak-user-management/src/components/CreateEditUserGroup/Form.tsx
packages/keycloak-user-management/src/components/CreateEditUserGroup/index.tsx
packages/keycloak-user-management/src/components/CreateEditUserGroup/tests/Form.test.tsx
packages/keycloak-user-management/src/components/CreateEditUserGroup/tests/fixtures.ts
packages/keycloak-user-management/src/components/CreateEditUserGroup/tests/utils.test.tsx
packages/keycloak-user-management/src/components/CreateEditUserGroup/utils.tsx
packages/keycloak-user-management/src/components/UserRolesList/index.tsx
packages/keycloak-user-management/src/components/UserRolesList/tests/fixtures.ts
packages/keycloak-user-management/src/components/UserRolesList/tests/index.test.tsx
packages/keycloak-user-management/src/ducks/userGroups.ts
packages/location-management/src/components/EditLocationUnit/index.tsx

- Redirect to user group list view upon creating new user group
- Redirect to user group list view after mapping roles to usergroups
- Remove roles description sorting
NB: The endless spinner shown upon location unit edit is addressed in [this PR](https://github.com/opensrp/web/pull/645)
addresses #649

649 fix bugs reported on zeir

---

app/package.json
packages/inventory/src/containers/CreateServicePoint/tests/index.test.tsx
packages/inventory/src/containers/EditServicePoint/tests/index.test.tsx
packages/location-management/package.json
packages/location-management/src/components/EditLocationUnit/index.tsx
packages/location-management/src/components/EditLocationUnit/tests/index.test.tsx
packages/location-management/src/components/LocationForm/tests/fixtures.ts
packages/location-management/src/components/LocationUnitList/index.tsx
packages/location-management/src/components/LocationUnitList/tests/index.test.tsx
packages/location-management/src/components/NewLocationUnit/index.tsx
packages/location-management/src/components/NewLocationUnit/tests/index.test.tsx

- refractor code to use useeffect like technique
- remove twice update in tests

Address comments on location Module

---

app/.env.sample
app/src/configs/env.ts
app/src/dispatchConfig.ts
docker/confd_env.toml
docker/config.js.tmpl
docs/env.md
packages/pkg-config/src/configStore/index.ts
packages/pkg-config/src/configStore/tests/index.test.tsx
packages/react-utils/src/helpers/componentUtils.tsx

- Adds FHIR base URL to app config state to be used by the new  fhir packages
Signed-off-by: Kipchirchir Sigei <arapgodsmack@gmail.com>

Set fhir base url to app config state

---

packages/team-management/src/components/TeamsAddEdit/Form.tsx
packages/team-management/src/components/TeamsAddEdit/index.tsx
packages/team-management/src/components/TeamsAddEdit/tests/Form.test.tsx
packages/team-management/src/components/TeamsAddEdit/tests/index.test.tsx

Fixes #667 
- plural practitioners prop
- show all practitioners ass add options on select
- use available team members as default select value
- use promise.all to fetch multiple requests in parallel
- fix getPractitionerDetail typo
- filter practitioners list for inactive users
- mock antd select and add tests for above

667 practitioners bugs

---

packages/team-assignment/src/components/ListView/index.tsx
packages/team-assignment/src/components/ListView/tests/index.test.tsx

closes #692 
- a61c0f2 wraps every wrapper update with act
- a7cbaead1e4dafec28e24f314d5fa4277b9cdaa5 watches for undefined option props
- eb48d21d8f6b4cc4e4adc291a0480db65ff1489b removes the useForm hook in favour of Form's initialValues prop

692 team assignment error on search

---

app/src/configs/env.ts
packages/keycloak-user-management/src/components/UserList/index.tsx
packages/keycloak-user-management/src/components/UserList/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/UserList/tests/index.test.tsx

Remove stowaway bracket

---

packages/keycloak-user-management/src/components/UserList/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/UserList/tests/__snapshots__/utils.test.tsx.snap
packages/keycloak-user-management/src/components/UserList/tests/index.test.tsx
packages/keycloak-user-management/src/components/UserList/tests/utils.test.tsx
packages/keycloak-user-management/src/components/UserList/utils.tsx

- closes #693 
- fix user management table column ordering
- return username column name

693 user table columns mismatch

---

packages/plan-form-core/src/formHelpers/activitiesLookup.ts
packages/plan-form-core/src/formHelpers/types.ts
packages/plan-form/src/Form/tests/__snapshots__/index.test.tsx.snap
packages/plan-form/src/Form/tests/fixtures.tsx

- updates the plan template as specified here:  https://github.com/opensrp/opensrp-client-eusm/issues/74

Client eusm Template update

---

packages/team-management/src/components/TeamsAddEdit/Form.tsx
packages/team-management/src/components/TeamsAddEdit/tests/index.test.tsx

closes #746 
- add search for team members list

add search for team members, add a test for search

---

packages/plan-form-core/src/formHelpers/activitiesLookup.ts
packages/plan-form/src/Form/tests/__snapshots__/index.test.tsx.snap
packages/plan-form/src/Form/tests/fixtures.tsx

Reference https://github.com/opensrp/opensrp-client-eusm/issues/80

Update plan template

---

packages/location-management/src/components/LocationUnitDetail/index.tsx
packages/location-management/src/components/LocationUnitDetail/tests/__snapshots__/index.test.tsx.snap
packages/location-management/src/components/LocationUnitDetail/tests/index.test.tsx
packages/location-management/src/lang.ts

- closes #706 
- add UUID to location units details

706 add UUID to location units

---

packages/keycloak-user-management/src/components/forms/UserForm/tests/index.test.tsx
packages/keycloak-user-management/src/components/forms/UserForm/tests/utils.test.tsx
packages/keycloak-user-management/src/components/forms/UserForm/utils.tsx

- closes #695 
- refactor edit/create keycloak user and practitioner functions
- also edit practitioner details to match user
- update and add tests

695 update practitioner name on keycloak user change

---

packages/keycloak-user-management/src/components/UserList/index.tsx
packages/keycloak-user-management/src/components/UserList/tests/index.test.tsx

- closes #714 
- stop infinite loader on user table sort

714 infinite loader on sort

---

packages/keycloak-user-management/src/components/forms/UserForm/tests/utils.test.tsx
packages/keycloak-user-management/src/components/forms/UserForm/utils.tsx

- closes #772 
- new practitioner should be active by default

772 practitioner active by default

---

app/src/containers/pages/Home/Home.tsx
app/src/containers/pages/Home/tests/__snapshots__/Home.test.tsx.snap

rename admin tile to users

---

packages/location-management/src/components/LocationForm/CustomSelect/index.tsx
packages/location-management/src/components/LocationForm/CustomSelect/tests/index.test.tsx
packages/location-management/src/components/LocationForm/tests/__snapshots__/index.test.tsx.snap

Fix search on location form unit group field
close #779

Fix search on location form unit group field

---

packages/team-assignment/src/ducks/assignments/index.ts
packages/team-assignment/src/ducks/assignments/tests/index.test.tsx

- closes #766 
- return all assignments regardless of date
- fix and add test

766 fix team assignments

---

Dockerfile

update express server branch to tag

---

.circleci/config.yml
.eslintrc.js
package.json
packages/location-management/src/components/LocationForm/tests/index.test.tsx

- Refactor long running lint command
- Refactor flaky form validation test `latitude/longitude`

[DNM] Fix CI

---

.circleci/config.yml

Add ability to reset cache via a circle ci env

Reset circle ci dependency cache

---

packages/fhir-care-team/src/components/CreateEditCareTeam/Form.tsx
packages/fhir-care-team/src/components/CreateEditCareTeam/index.tsx
packages/fhir-care-team/src/components/CreateEditCareTeam/tests/__snapshots__/index.test.tsx.snap
packages/fhir-care-team/src/components/CreateEditCareTeam/tests/fixtures.ts
packages/fhir-care-team/src/components/CreateEditCareTeam/tests/form.test.tsx
packages/fhir-care-team/src/components/CreateEditCareTeam/tests/form.unmocked.test.tsx
packages/fhir-care-team/src/components/CreateEditCareTeam/tests/index.test.tsx

- closes #835 
- filter out inactive practitioners from  care team assignment 
- filter practitioners by text
- part of https://github.com/opensrp/web/issues/770

Filter care teams practitioners

---

packages/react-utils/package.json
packages/react-utils/src/helpers/dataLoaders.ts
packages/react-utils/src/helpers/tests/dataLoaders.test.ts
packages/react-utils/src/helpers/tests/fixtures.ts
setupTests.js

- Build a generic service class around `FHIR.client` instance for performing CRUD operations againt HAPI server

Add FHIR service class

---

packages/fhir-client/src/components/DocumentReference/helpers/components.tsx
packages/fhir-client/src/components/DocumentReference/helpers/utils.ts
packages/fhir-client/src/components/DocumentReference/index.tsx
packages/fhir-client/src/components/DocumentReference/tests/__snapshots__/index.test.tsx.snap
packages/fhir-client/src/components/DocumentReference/tests/docReference.json
packages/fhir-client/src/components/DocumentReference/tests/index.test.tsx
packages/fhir-client/src/components/PatientDetails/index.tsx
packages/fhir-client/src/components/helpers/testUtils.tsx
packages/fhir-client/src/constants.ts
packages/fhir-client/src/index.css

Refactors the DocReference ui.
- Uses an Accordion that collapses to show a DocReference resource full details.

Enhance DocReference component

---

packages/card-support/package.json
packages/card-support/src/components/DownloadClientData/index.tsx
packages/card-support/src/components/DownloadClientData/tests/__snapshots__/index.test.tsx.snap
packages/card-support/src/components/DownloadClientData/tests/fixtures.ts
packages/card-support/src/components/DownloadClientData/tests/index.test.tsx
packages/card-support/src/constants.ts
packages/card-support/src/lang.ts
yarn.lock

- closes #900 
- get location hierarchy of logged in user from team assignments ( keycloak user -> practitioner -> team assigned to ->  location assigned to team -> location hierarchy for location)

fix card support location hierarchy

---

packages/card-support/package.json
packages/card-support/src/components/DownloadClientData/index.tsx
packages/card-support/src/components/DownloadClientData/tests/fixtures.ts
packages/card-support/src/components/DownloadClientData/tests/index.test.tsx
packages/card-support/src/constants.ts
packages/card-support/src/lang.ts
yarn.lock

Reverts opensrp/web#907
- Found better approach here https://github.com/opensrp/web/pull/908

Revert "fix card support location hierarchy"

---

jest.config.js
package.json
packages/fhir-quest-form/README.md
packages/fhir-quest-form/package.json
packages/fhir-quest-form/src/index.tsx
packages/fhir-quest-form/src/tests/fixtures/index.tsx
packages/fhir-quest-form/src/tests/index.test.tsx
packages/fhir-quest-form/tsconfig.json
packages/react-utils/src/components/KeyValuePairs/index.css
packages/react-utils/src/components/KeyValuePairs/index.tsx
packages/react-utils/src/components/KeyValuePairs/tests/index.test.tsx
packages/react-utils/src/index.tsx
patches/@helsenorge+skjemautfyller+7.11.0-prerelease2.patch
yarn.lock

Base  Branch containing Fhir quest work.
part of #870 
This pr:
- Adds two components in react-utils to be later used in the questionnaire views to render key value pair information
- A patch for @helsenorge node_module package bug
- A small jest config tweaks
- Adds the view that pulls questionnaire and questionnaireResponse resources and render them as a form

Fhir QuestForm

---

packages/card-support/src/components/DownloadClientData/tests/utils.test.tsx
packages/card-support/src/components/DownloadClientData/utils.tsx

get missing client location names from already fetched location hierarchies

---

packages/fhir-care-team/src/components/CreateEditCareTeam/Form.tsx
packages/fhir-care-team/src/components/CreateEditCareTeam/index.tsx
packages/fhir-care-team/src/components/CreateEditCareTeam/tests/__snapshots__/index.test.tsx.snap
packages/fhir-care-team/src/components/CreateEditCareTeam/tests/index.test.tsx
packages/fhir-care-team/src/components/CreateEditCareTeam/utils.tsx
packages/fhir-care-team/src/constants.tsx
packages/react-utils/src/helpers/utils.tsx

Resolves initialValues after loading is complete. 
Update tests to use nock and RTL

[Bug Fix] Add edit care team view

---

packages/keycloak-user-management/src/components/UserList/TableActions/index.tsx
packages/keycloak-user-management/src/components/UserList/TableActions/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/UserList/TableActions/tests/index.test.tsx
packages/keycloak-user-management/src/components/UserList/TableActions/tests/utils.test.tsx
packages/keycloak-user-management/src/components/UserList/index.tsx
packages/keycloak-user-management/src/components/UserList/tests/index.test.tsx
packages/keycloak-user-management/src/constants.ts

close #957 
Invalidate user list after deleting user

Invalidate user list after deleting user

---

packages/location-management/src/components/LocationUnitList/index.tsx
packages/location-management/src/components/LocationUnitList/tests/index.test.tsx

close #953
close loader depending on request resolution only

Do no show eternal loader in locations

---

app/src/App/App.tsx
app/src/components/Logout/index.tsx
app/src/components/Logout/tests/__snapshots__/index.test.tsx.snap
app/src/components/page/CustomCallback/index.tsx
packages/fhir-care-team/src/components/ListView/index.tsx
packages/fhir-location-management/src/components/LocationUnitDetail/index.tsx
packages/fhir-location-management/src/components/LocationUnitList/index.tsx
packages/fhir-quest-form/src/index.tsx
packages/form-config-antd/src/components/DraftFileList/index.tsx
packages/form-config-antd/src/components/FileList/index.tsx
packages/form-config-antd/src/components/ReleaseList/index.tsx
packages/inventory/src/containers/InventoryAddEdit/index.tsx
packages/inventory/src/containers/ServicePointProfile/index.tsx
packages/keycloak-user-management/src/components/CreateEditUser/index.tsx
packages/keycloak-user-management/src/components/CreateEditUserGroup/index.tsx
packages/keycloak-user-management/src/components/UserGroupsList/index.tsx
packages/keycloak-user-management/src/components/UserRolesList/index.tsx
packages/location-management/src/components/EditLocationUnit/index.tsx
packages/location-management/src/components/LocationUnitGroupAddEdit/Form.tsx
packages/location-management/src/components/LocationUnitGroupList/index.tsx
packages/location-management/src/components/LocationUnitList/index.tsx
packages/location-management/src/components/NewLocationUnit/index.tsx
packages/location-settings/src/components/LocationSettingsView/index.tsx
packages/reports/src/components/DistrictReport/index.css
packages/reports/src/components/DistrictReport/index.tsx
packages/team-assignment/src/components/ListView/index.tsx
packages/team-management/src/components/TeamsAddEdit/index.tsx

Center Spin-Loaders
close #947

Center loaders

---

packages/fhir-team-management/src/components/OrganizationAffiliation/Form.tsx
packages/fhir-team-management/src/components/OrganizationAffiliation/tests/__snapshots__/index.test.tsx.snap
packages/fhir-team-management/src/components/OrganizationAffiliation/tests/index.test.tsx
packages/fhir-team-management/src/components/OrganizationAffiliation/utils.ts

Filter org selection; hide modal popup on save
close #949

Hide assingment modal after succesful save

---

packages/fhir-quest-form/package.json
yarn.lock

This reverts commit 19b796c6579d3f98d1d3fdac5bed53eb20ad1349.

Revert "Bump marked from 0.7.0 to 4.0.10"

---

app/package.json

- add fhir user management, and fhir client as dependencies

add missing dependencies

---

docs/env.md

Add docs for missing envs

---

app/src/App/App.tsx
packages/keycloak-user-management/src/components/UserGroupDetailView/index.tsx

Problem: UserGroups and userList views are not showing up correctly.
Reason: The way urls are nested, the User View is matched first for routes that should match the `UserGroups`, and `UserList` views 
Fix: this pr.

Fix route placement

---

packages/location-management/src/components/EditLocationUnit/index.tsx
packages/location-management/src/components/EditLocationUnit/tests/index.test.tsx
packages/location-management/src/components/NewLocationUnit/index.tsx
packages/location-management/src/components/NewLocationUnit/tests/index.test.tsx

Fix eternal loader in addEdit location view in `@openssrp/location-management` package.
close #969

Fix eternal loader in addEdit location view

---

app/src/configs/env.ts

Read opensrp roles config correctly in envs
close #942

Read opensrp roles config correctly in envs

---

packages/team-management/src/components/TeamsView/index.tsx
packages/team-management/src/components/TeamsView/tests/index.test.tsx
packages/team-management/src/ducks/tests/fixtures.ts

close #951 
Removes invalid assignments when rendering teamDetail view

Sanitize assignments fetched in team detail view

---

packages/fhir-views/package.json
packages/fhir-views/src/QuestionnaireList/index.tsx
packages/fhir-views/src/QuestionnaireResponseList/index.tsx
packages/fhir-views/src/mls.ts

- Add localization support in fhir-views

Add localization support in fhir-views

---

packages/fhir-client/package.json
packages/fhir-client/src/components/DocumentReference/utils/components.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/CarePlan.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/Condition.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/DiagnosticReport.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/Encounter.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/Goal.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/Immunization.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/ImmunizationRecommendation.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/Location.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/Medication.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/MedicationAdministration.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/MedicationRequest.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/MedicationStatement.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/Observation.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/Organization.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/Patient.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/Practitioner.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/Procedure.tsx
packages/fhir-client/src/components/PatientDetails/ResourceSchema/ServiceRequest.tsx
packages/fhir-client/src/components/PatientDetails/index.tsx
packages/fhir-client/src/components/PatientsList/index.tsx
packages/fhir-client/src/mls.ts

Update Translations in fhir client package

Update Translations in fhir client package

---

packages/fhir-keycloak-user-management/src/components/CreateEditUser/index.tsx
packages/fhir-keycloak-user-management/src/components/UserList/ListView/index.tsx
packages/fhir-keycloak-user-management/src/components/UserList/ListView/tableColumns.tsx
packages/fhir-keycloak-user-management/src/components/UserList/ListView/utils.tsx
packages/fhir-keycloak-user-management/src/components/UserList/ViewDetails/index.tsx
packages/fhir-keycloak-user-management/src/mls.ts
packages/keycloak-user-management/src/components/forms/UserForm/types.ts

Add localization support to fhir-user management package

Add localization support to fhir-user management package

---

packages/fhir-quest-form/package.json
packages/fhir-quest-form/src/index.tsx
packages/fhir-quest-form/src/mls.ts

- Add localization support for quest form

Add localization support for quest form

---

.github/codecov.yml
README.md

close #977
Add codecov.yml file - Enforce coverage thresholds

Add codecov.yml file - Enforce coverage thresholds

---

.husky/pre-commit
package.json
yarn.lock

part of #930 
Add husky pre-commit hook

Add husky hooks

---

packages/fhir-care-team/src/components/ListView/index.tsx
packages/fhir-group-management/src/components/GroupList/index.tsx
packages/fhir-keycloak-user-management/src/components/UserList/ListView/tableColumns.tsx
packages/fhir-keycloak-user-management/src/components/UserList/ViewDetails/index.tsx

- disable group search (not fully scoped out for fhir)
- fix wrong column ordering
- different warning color for missing practitioners and care teams

585 fhir user management

---

Dockerfile

Bump express version to v1.3.5

Bump express version to v1.3.5

---

packages/fhir-care-team/src/components/CreateEditCareTeam/Form.tsx
packages/fhir-care-team/src/components/CreateEditCareTeam/index.tsx
packages/fhir-care-team/src/components/CreateEditCareTeam/tests/fixtures.ts
packages/fhir-care-team/src/components/CreateEditCareTeam/tests/index.test.tsx
packages/fhir-care-team/src/components/CreateEditCareTeam/utils.tsx

close #1016
Fix how care team initial values are computed, And how the corresponding response payload is built.

Fix how care team initial values are computed

---

Dockerfile

update express server branch for redis session storage compartibility

---

.github/workflows/cd-test.yml
.github/workflows/docker-docs.yml
.github/workflows/docker-publish.yml
docs/how-to-use-docker-image.md

- Adds a github action workflow which updates dockerhub readme.
- `docs/how-to-use-docker-image.md` has the contents of dockerhub readme.

Add docker docs ci

---

packages/fhir-location-management/src/components/LocationForm/index.tsx
packages/fhir-location-management/src/components/LocationUnitList/index.tsx
packages/react-utils/src/helpers/dataLoaders.ts
packages/react-utils/src/helpers/tests/dataLoaders.integration.test.ts
packages/react-utils/src/helpers/tests/dataLoaders.test.ts

Fix Location Hierarchy update on add/edit action

---

app/src/App/tests/App.test.tsx
app/src/components/Logout/tests/index.test.tsx
app/src/components/page/Header/index.tsx
app/src/configs/__mocks__/env.ts
app/src/containers/ConnectedHeader/tests/__snapshots__/index.test.tsx.snap
app/src/containers/ConnectedHeader/tests/index.test.tsx

Login url should be `fe/login` when we are using the express backend

Fix login url when backend active is true

---

Dockerfile

- Bump express tag in DockerFile

Bump express tag in DockerFile

---

app/package.json
packages/keycloak-user-management/package.json
packages/opensrp-store/package.json
packages/react-utils/package.json
yarn.lock

Update gatekeeper package version.

Update gatekeeper package version

---

packages/fhir-group-management/src/components/BaseComponents/BaseGroupsListView/index.tsx
packages/fhir-group-management/src/components/BaseComponents/GroupDetail/index.tsx
packages/fhir-group-management/src/components/CommodityList/index.tsx
packages/fhir-group-management/src/components/CommodityList/tests/index.test.tsx
packages/fhir-group-management/src/components/GroupList/index.tsx

Fix viewDetails close button redirection for commodity module

Fix viewDetails close button redirection for commodity module

---

app/src/App/App.tsx
app/src/containers/pages/Home/Home.tsx
app/src/containers/pages/Home/tests/Home.test.tsx
app/src/containers/pages/Home/tests/__snapshots__/Home.test.tsx.snap

- closes https://github.com/opensrp/web/issues/1073
- turn user management card off by default
- toggle based on env as opposed to roles
- remove no longer needed props

turn user management card off by default

---

package.json
packages/fhir-keycloak-user-management/src/components/UserList/ListView/tableColumns.tsx
packages/fhir-keycloak-user-management/src/components/UserList/ListView/tests/__snapshots__/index.test.tsx.snap
packages/fhir-keycloak-user-management/src/components/UserList/ListView/tests/index.test.tsx
packages/fhir-keycloak-user-management/src/components/UserList/ViewDetails/index.tsx
packages/fhir-keycloak-user-management/src/components/UserList/ViewDetails/tests/index.test.tsx
packages/fhir-keycloak-user-management/src/constants.ts
packages/fhir-location-management/src/components/LocationUnitList/Table.tsx
packages/fhir-location-management/src/components/LocationUnitList/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/CreateEditUser/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/CreateEditUser/tests/index.test.tsx
packages/keycloak-user-management/src/components/CreateEditUserGroup/Form.tsx
packages/keycloak-user-management/src/components/CreateEditUserGroup/form.css
packages/keycloak-user-management/src/components/UserGroupDetailView/index.tsx
packages/keycloak-user-management/src/components/UserGroupDetailView/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/UserGroupDetailView/tests/index.test.tsx
packages/keycloak-user-management/src/components/UserGroupsList/index.tsx
packages/keycloak-user-management/src/components/UserList/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/UserList/tests/__snapshots__/utils.test.tsx.snap
packages/keycloak-user-management/src/components/UserList/tests/index.test.tsx
packages/keycloak-user-management/src/components/UserList/utils.tsx
packages/keycloak-user-management/src/components/forms/UserForm/index.tsx
packages/keycloak-user-management/src/components/forms/UserForm/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/forms/UserForm/tests/index.test.tsx
packages/keycloak-user-management/src/index.tsx
packages/location-management/src/components/LocationUnitGroupList/Table.tsx
packages/location-management/src/components/LocationUnitList/Table.tsx
packages/team-management/src/components/TeamsView/Table.tsx
yarn.lock

- closes #1082 
- Add user group members to view details section
- Fix alignment of action columns on a few tables.
-  Remove email column

Patch user management

---

app/src/routes/index.tsx
packages/fhir-location-management/src/components/LocationForm/index.tsx
packages/fhir-location-management/src/components/LocationForm/tests/__snapshots__/index.test.tsx.snap
packages/fhir-location-management/src/components/LocationForm/tests/index.test.tsx
packages/fhir-location-management/src/components/LocationForm/utils.ts
packages/fhir-location-management/src/components/LocationUnitDetail/index.tsx
packages/fhir-location-management/src/components/LocationUnitList/Table.tsx
packages/fhir-location-management/src/components/LocationUnitList/tests/__snapshots__/index.test.tsx.snap
packages/react-utils/src/components/CommonStyles/index.css

close #1081 
- Re-order location.status options in form, make active selected for new locations by default.
- update fields  shown in location details section
- Disable location Unit Group when using fhir locations

Fhir Location update

---

packages/fhir-keycloak-user-management/src/components/CreateEditUser/index.tsx
packages/fhir-keycloak-user-management/src/components/CreateEditUser/tests/fixtures.ts
packages/fhir-keycloak-user-management/src/components/CreateEditUser/tests/index.test.tsx
packages/fhir-keycloak-user-management/src/components/UserList/ListView/tests/fixtures.ts
packages/fhir-keycloak-user-management/src/components/UserList/ListView/tests/index.test.tsx
packages/fhir-keycloak-user-management/src/components/UserList/ListView/utils.tsx

- closes https://github.com/opensrp/web/issues/1094
- closes https://github.com/opensrp/web/issues/1102
- part of https://github.com/opensrp/web/issues/1103

create group resource when you create user

---

packages/fhir-care-team/src/components/CreateEditCareTeam/utils.tsx

reuse care team uuid for id resource on create, use existing on edit

---

packages/fhir-care-team/src/components/CreateEditCareTeam/tests/fixtures.ts
packages/fhir-care-team/src/components/CreateEditCareTeam/tests/form.unmocked.test.tsx
packages/fhir-care-team/src/components/CreateEditCareTeam/utils.tsx

fix broken test

---

README.md
docs/CONTRIBUTING.md

- Add a contributing guide doc
- part of https://github.com/opensrp/web/issues/792

Add a contributing doc file

---

README.md
docs/CONTRIBUTING.md
docs/getting-started.md

- part of https://github.com/opensrp/web/issues/792

add fhir web getting started docs

---

packages/fhir-location-management/src/components/LocationForm/tests/fixtures.ts
packages/fhir-location-management/src/components/LocationForm/tests/index.test.tsx
packages/fhir-location-management/src/components/LocationForm/utils.ts

- close #1168 
- Fix bug assign uuids to new locations

Fix bug assign uuids to new locations

---

docs/how-to-use-docker-image.md
docs/opensrp-web-docker-deployment.md

- adapt old documentation for opensrp web only
- part of https://github.com/opensrp/web/issues/792

adapt old documentation for opensrp web

---

package.json
packages/fhir-keycloak-user-management/src/components/CreateEditUser/tests/fixtures.ts
packages/fhir-keycloak-user-management/src/components/CreateEditUser/tests/index.test.tsx
packages/keycloak-user-management/src/components/forms/UserForm/index.tsx
packages/keycloak-user-management/src/components/forms/UserForm/tests/fixtures.ts
packages/keycloak-user-management/src/components/forms/UserForm/tests/index.unmocked.test.tsx
packages/keycloak-user-management/src/components/forms/UserForm/types.ts
packages/keycloak-user-management/src/components/forms/UserForm/utils.tsx
packages/keycloak-user-management/src/constants.ts
packages/keycloak-user-management/src/ducks/user.ts
packages/react-utils/src/components/FhirSelect/index.tsx
packages/react-utils/src/components/FhirSelect/tests/fixtures.ts
packages/react-utils/src/components/FhirSelect/tests/index.test.tsx
packages/react-utils/src/components/FhirSelect/utils.ts
packages/react-utils/src/index.tsx
setupTests.js

- close #1147 
- Adds a fhir select component with async search support
- Uses the select componet as the backing form field for selecting fhir core application id in user management.

Add a form field to add fhir core app id to users during usre creation

---

README.md
docs/CONTRIBUTING.md
docs/fhir-web-docker-deployment.md
docs/getting-started.md

- closes https://github.com/opensrp/web/issues/792
- collate all documentations written so far into readme

Add documentation links to readme

---

.github/workflows/cd-test.yml
packages/fhir-location-management/src/components/AddEditLocationUnit/tests/index.test.tsx
packages/fhir-team-management/src/components/AddEditOrganization/tests/index.test.tsx

- Wait for view to be actionable in test.

Fix flaky test

---

packages/inventory/src/components/InventoryList/index.tsx
packages/inventory/src/components/InventoryList/tests/index.test.tsx
packages/opensrp-reducer-factory/src/index.ts
packages/opensrp-reducer-factory/src/tests/index.test.ts

- Overwrite entries in the inventory slice with each refresh.
- closes #1186

Auto refresh inventory List

---

.github/ISSUE_TEMPLATE/opensrp-web-deployment-support.yml

- Add modules that can be requested to be added as `extra functionality`
- Formats yml file.
- closes #1196

Update deployment support issue form

---

app/src/App/tests/App.test.tsx
app/src/containers/pages/Home/Home.tsx
app/src/containers/pages/Home/tests/Home.test.tsx
app/src/containers/pages/Home/tests/__snapshots__/Home.test.tsx.snap
app/src/routes/index.tsx
app/src/routes/tests/index.test.tsx

- close #1151 
- Generate the home view call to action buttons from enabled routes.
- A few styling tweaks to make the grid responsive.

Refactor the home view

---

app/src/components/page/Sidebar/utils.tsx

This adds the logic to assign an active key when the path matches a route,
closes #1223

Add logic for matching urls

---

packages/fhir-team-management/src/components/AddEditOrganization/utils.ts
packages/fhir-team-management/src/components/OrganizationList/ListView/tests/index.test.tsx
packages/fhir-team-management/src/components/OrganizationList/ViewDetails/index.tsx

Adds a util function to check for the assigned locations for an organization.
closes #1228

Add function to find assigned locations for an organization

---

Dockerfile

Update express version in Dockerfile

Update express version in Dockerfile

---

README.md

Update the development branch for opensrp-1
Also added branch protection rules for `opensrp-1`

Update the development branch for opensrp-1

---

packages/fhir-location-management/src/components/AddEditLocationUnit/tests/index.test.tsx
packages/fhir-location-management/src/components/LocationForm/index.tsx

The issue was a regression fixed in another pr : #1274. This just adds a small change to invalidate queries keyed by locationResourceType as well, and adds a test to prevent future regression.
close #1277

Fix location creation bug

---

packages/fhir-location-management/src/components/LocationForm/index.tsx

close #1289 
Allow users to clear part of selection

Allow users to clear part of selection

---

packages/fhir-location-management/src/components/LocationUnitList/index.tsx
packages/fhir-location-management/src/components/LocationUnitList/tests/index.test.tsx
packages/fhir-location-management/src/components/RootLocationWizard/index.tsx
packages/fhir-location-management/src/components/RootLocationWizard/tests/fixtures.ts
packages/fhir-location-management/src/helpers/utils.ts

close #1245`
Add a wizard-ish view that allows users to create the root fhir location from web.

Prompt user to create root location if its not uploaded yet.

---

app/src/App/fhir-apps.tsx

Fix permission required for Gropu list view

---

packages/i18n/package.json

Closes #1301
- fix build script command 
This had regressed since https://github.com/onaio/fhir-web/pull/1239/files#diff-b521a60001d6c012f4a294bdba3be54c1e1a6aa8a059fb2d3b0fd4e41ec5c5a4

Fix build script in i18n package

---

packages/fhir-helpers/src/utils/utils.ts
packages/fhir-location-management/src/components/ViewDetails/DetailsTabs/Inventory.tsx
packages/fhir-location-management/src/components/ViewDetails/utils.ts

- Explicitly add undefined types to stop lint from removing null checks

Fix lint removing null checks

---

packages/fhir-helpers/src/constants/codeSystems.ts
packages/fhir-keycloak-user-management/package.json
packages/fhir-keycloak-user-management/src/components/CreateEditUser/index.tsx
packages/fhir-keycloak-user-management/src/components/CreateEditUser/tests/fixtures.ts
yarn.lock

**closes #1350**
- Add keycloak coding on practitioner resource secondary identifier
**Checklist**

Update practitioner Keycloak secondary identifier coding

---

app/src/containers/ConnectedHeader/tests/__snapshots__/index.test.tsx.snap
packages/i18n/package.json
packages/i18n/src/init.tsx
packages/i18n/src/tests/init.test.tsx
yarn.lock

**closes #1332**
- Use `i18next-browser-languageDetector` package to persist user selected language on browser storage
**Checklist**

Persist user selected language

---

packages/fhir-group-management/package.json
packages/fhir-group-management/src/components/LocationInventory/form.tsx
packages/fhir-group-management/src/components/LocationInventory/tests/form.test.tsx
packages/fhir-group-management/src/constants.tsx
packages/fhir-helpers/src/constants/codeSystems.ts
packages/fhir-location-management/src/components/AddEditLocationUnit/tests/eusm.test.tsx
packages/fhir-location-management/src/components/LocationForm/index.tsx
packages/fhir-location-management/src/constants.ts
packages/react-utils/src/components/AsyncSelect/ValueSetAsyncSelect/index.tsx
packages/react-utils/src/components/AsyncSelect/ValueSetAsyncSelect/tests/index.test.tsx
yarn.lock

**closes #1374**
- Updates valueset server URL
**Checklist**

Update valueset async select component

---

packages/fhir-location-management/src/components/AddEditLocationUnit/base.tsx
packages/fhir-location-management/src/components/AddEditLocationUnit/tests/eusm.test.tsx
packages/fhir-location-management/src/components/AllLocationListFlat/core.tsx
packages/fhir-location-management/src/components/ViewDetails/LocationDetails/index.tsx
packages/fhir-location-management/src/constants.ts

**closes #1378**
- Update Location Add Edit view to accept a back path as param
- This will be used to override the default form cancel behavour
**Checklist**

Update Add and Edit Location view

---

packages/fhir-location-management/src/components/ViewDetails/LocationDetails/index.tsx

Fix unused param lint error

---

packages/fhir-group-management/src/components/CommodityAddEdit/Default/utils.ts
packages/fhir-group-management/src/components/CommodityAddEdit/Eusm/index.tsx
packages/fhir-group-management/src/components/CommodityAddEdit/Eusm/tests/__snapshots__/index.test.tsx.snap
packages/fhir-group-management/src/components/CommodityAddEdit/Eusm/tests/index.test.tsx
packages/fhir-group-management/src/components/CommodityAddEdit/Eusm/utils.ts
packages/fhir-group-management/src/components/ProductForm/utils.tsx
packages/fhir-helpers/src/constants/valueSetEnums.ts

**closes #1404 **
Provides a statically defined initial value and hide the field.
waiting on: https://github.com/onaio/fhir-web/issues/1404#issuecomment-2120122034

Prepolate type field in product form

---

packages/fhir-group-management/src/components/LocationInventory/tests/fixtures.ts
packages/fhir-group-management/src/components/LocationInventory/tests/utils.test.tsx
packages/fhir-group-management/src/components/LocationInventory/utils.tsx

Fix serial num is only required for attractive products

---

packages/fhir-client/src/components/PatientDetails/PopulatedTableTabs/tests/__snapshots__/index.test.tsx.snap
packages/fhir-client/src/components/PatientDetails/tests/index.test.tsx

- Updates failing test from pr #1405 
- Date format was updated and some tests didn't get updated

Update failing tests

---

packages/react-utils/src/helpers/dataLoaders.ts
packages/react-utils/src/helpers/tests/dataLoaders.test.ts

**closes #1424**
update headers for `FhirServiceClass` request method
**Checklist**

Refactor fhir requests content-type to application/fhir+json

---

packages/react-utils/src/components/PrivateRoute/index.tsx
packages/react-utils/src/components/PrivateRoute/tests/index.test.tsx

**closes #1336**
**Checklist**

Fix paths not resolving after login / refresh

---

.github/workflows/cd-test.yml

Has fix for buggy jest garbage collection that resulted in memory leaks

Update node version used for testing

---

packages/fhir-location-management/src/components/AllLocationListFlat/core.tsx
packages/fhir-location-management/src/components/AllLocationListFlat/tests/utils.test.tsx
packages/fhir-location-management/src/components/AllLocationListFlat/utils.tsx
packages/fhir-location-management/src/components/EditLink/index.tsx
packages/fhir-location-management/src/components/EditLink/tests/fixtures.ts
packages/fhir-location-management/src/components/EditLink/tests/index.test.tsx
packages/fhir-location-management/src/components/ViewDetails/DetailsTabs/ChildLocations.tsx
packages/fhir-location-management/src/components/ViewDetails/LocationDetails/index.tsx

**closes #1443**
**Checklist**

Fix service point edits

---

Dockerfile

Bump express server version to v2.1.0

Bump express server version to v2.1.0

---

Dockerfile
packages/fhir-import/src/constants.ts
packages/fhir-import/src/containers/StartImportView/form.tsx

Update path in dockerfile

---

Dockerfile

**closes #**
Provide list id when uploading products and inventory

Provide list id when uploading products and inventory

---

Dockerfile

https://github.com/nodejs/node/issues/54518#issuecomment-2307687124wq

Downgrade node version in final step

---

.github/workflows/cd-test.yml
.github/workflows/docker-docs.yml
.github/workflows/docker-publish.yml

**closes #**
- Update the versions of dependent actions
- Update cache when building image
- Add a vulnerability check using docker scout.
relates:
- #1327 
- #627

Update gh actions

---

.github/workflows/docker-publish.yml

Fix yaml lint issue in github workflow

Fix yaml lint issue

---

packages/fhir-location-management/src/components/AllLocationListFlat/base.tsx
packages/fhir-location-management/src/components/AllLocationListFlat/dataGridFilterRow.tsx
packages/fhir-location-management/src/components/AllLocationListFlat/eusm.tsx

**closes #1478 **
Removes the parent location search on the service inventory page.
**Checklist**

Remove parent location filter from the service point list view

---

packages/react-utils/src/hooks/useServerSideActionsDataGrid.ts

- **closes #1494**
**Checklist**

Enable data refetch once a component remounts after a form update

---

packages/fhir-group-management/src/components/CommodityAddEdit/Eusm/tests/__snapshots__/index.test.tsx.snap
packages/fhir-group-management/src/components/CommodityAddEdit/Eusm/tests/fixtures.ts
packages/fhir-group-management/src/components/CommodityAddEdit/Eusm/tests/index.test.tsx
packages/fhir-group-management/src/components/CommodityAddEdit/Eusm/utils.ts
packages/fhir-group-management/src/components/LocationInventory/form.tsx
packages/fhir-group-management/src/components/LocationInventory/tests/form.test.tsx
packages/fhir-group-management/src/components/ProductForm/index.tsx
packages/fhir-healthcare-service/src/components/HealthCareAddEdit/Form.tsx

- **closes #1488**
Add asterisks for all required fields on forms
**Checklist**

Add asterisks for all required fields on forms

---

package.json
yarn.lock

up lerna to version whose dependency `@parcel/watcher` is compatible with arm platforms

Up the lerna version

---

packages/fhir-keycloak-user-management/src/components/CreateEditUser/index.tsx
packages/fhir-keycloak-user-management/src/components/CreateEditUser/tests/new-user.test.tsx
packages/keycloak-user-management/src/components/CreateEditUser/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/Credentials/index.tsx
packages/keycloak-user-management/src/components/Credentials/tests/__snapshots__/index.test.tsx.snap
packages/keycloak-user-management/src/components/forms/UserForm/index.tsx
packages/keycloak-user-management/src/components/forms/UserForm/tests/fixtures.ts
packages/keycloak-user-management/src/components/forms/UserForm/tests/index.test.tsx
packages/keycloak-user-management/src/components/forms/UserForm/tests/index.unmocked.test.tsx
packages/keycloak-user-management/src/components/forms/UserForm/tests/utils.test.tsx
packages/keycloak-user-management/src/components/forms/UserForm/types.ts
packages/keycloak-user-management/src/components/forms/UserForm/utils.tsx
packages/keycloak-user-management/src/constants.ts

**closes #1524 **
- Enables adding credentials during user creation.
**Checklist**

Add password during user creation.

---

app/src/App/App.tsx
app/src/components/antdLocaleProvider/index.tsx
app/src/components/page/Header/index.tsx

Link antds locale provisioning with rest of the apps ii18n
