- package.json
Closes #87
Changed the lint-staged file filter for .ts files to ignore .d.ts files in dist folders
> Resolve dist folders throwing lint warning during commit

- .gitignore
- package.json
This change allows Ansible deployment to proceed with minimal modifications to the Ansible role https://github.com/onaio/ansible-react that is used for deploying this application.
> Add build script command to root package.json

- packages/opensrp-server-service/dist/serviceClass.js
- packages/opensrp-server-service/dist/types/serviceClass.d.ts
- packages/opensrp-server-service/src/serviceClass.ts
- packages/opensrp-server-service/src/tests/index.test.ts
closes #110
Accept the access token in the constructor so as to build the headers. The previous implementation made method getFetchOptions unusable since getDefaultHeaders was being called with the same default value for accessToken
> Add access token as part of OpenSRPService instance initialization args

- packages/opensrp-server-service/src/serviceClass.ts
- packages/opensrp-server-service/src/tests/index.test.ts
Make sure special chars in query params  are not escaped when making API calls 
Example code
```
service.list({ is_jurisdiction: true, attribute: 'card_status:needs_card' });
```
Before the string was being escaped when making the API call e.g `https://opensrp-stage.smartregister.org/opensrp/rest/location?is_jurisdiction=true&attribute=card_status%3Aneeds_card'`
Now that is resolved and the result is `https://opensrp-stage.smartregister.org/opensrp/rest/location?is_jurisdiction=true&attribute=card_status:needs_card'`
> Modify OpensrpService class to make sure special chars are not escaped

- packages/opensrp-plans/src/components/NewPlan/index.tsx
- packages/opensrp-plans/src/components/NewPlan/tests/index.test.tsx
- packages/opensrp-plans/src/components/UpdatePlan/index.tsx
- packages/opensrp-plans/src/components/UpdatePlan/tests/index.test.tsx
- packages/opensrp-plans/src/constants.tsx
- packages/opensrp-plans/src/helpers/common.ts
- packages/opensrp-plans/src/helpers/tests/utils.test.tsx
- packages/plan-form/README.md
- packages/plan-form/src/Form/index.tsx
- packages/plan-form/src/Form/tests/index.test.tsx
Support redirecting to different routes in plan-form, 
this is in order to support the different plan listing pages, such that creating a  plan will take the user to the list page of the plans of the same status
> Enhance planform routes

- client/src/components/page/Sidebar/index.tsx
- client/src/constants.tsx
Fix: #165 
Match Missions/Plans menu with Mockup. I've consistently named plans knowing  this will be translated in the future on a project basis
Here is the comment 
https://github.com/OpenSRP/web/issues/165#issuecomment-742817959
Current UI
> Missions sidemenu tweaks

- packages/keycloak-user-management/src/components/Credentials/index.tsx
- packages/keycloak-user-management/src/components/Credentials/tests/__snapshots__/index.test.tsx.snap
- packages/keycloak-user-management/src/constants.tsx
> Add user name on Credentials page

- packages/location-management/src/components/LocationUnitAddEdit/index.tsx
fix extra fields initial state when editing a location by appending all of the location properties into the initial formfields instead of picking one by one
Close #337
> fix extra fields initial state when editing location unit

- packages/keycloak-user-management/src/components/Credentials/index.tsx
- packages/keycloak-user-management/src/components/Credentials/tests/index.test.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/index.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/tests/__snapshots__/index.test.tsx.snap
- packages/keycloak-user-management/src/components/forms/UserForm/tests/utils.test.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/utils.tsx
The practitioners endpoint was throwing 400. This was because userId attribute was not being submitted as part of the request payload. The switch toggle was also not being checked on loading the form when editing a user who is marked as practitioner
> Solve 400 error when editing user

- packages/form-config/src/components/Antd/UploadForm/tests/index.test.tsx
- packages/form-config/src/components/Antd/UploadForm/tests/utils.test.tsx
- packages/form-config/src/components/Antd/UploadForm/utils.tsx
Addresses #358
Show server response if the API responds with an error when uploading a form
> Display server response as notification error if upload form fails

- app/src/App/utils.tsx
- packages/inventory/src/containers/CreateServicePoint/index.tsx
- packages/inventory/src/containers/CreateServicePoint/tests/index.test.tsx
- packages/inventory/src/containers/EditServicePoint/index.tsx
- packages/inventory/src/containers/EditServicePoint/tests/index.test.tsx
- packages/inventory/src/helpers/utils.tsx
- packages/location-management/src/components/EditLocationUnit/tests/__snapshots__/index.test.tsx.snap
- packages/location-management/src/components/LocationForm/index.tsx
- packages/location-management/src/components/LocationForm/tests/__snapshots__/index.test.tsx.snap
- packages/location-management/src/components/LocationForm/tests/fixtures.ts
- packages/location-management/src/components/LocationForm/tests/index.test.tsx
- packages/location-management/src/components/LocationForm/tests/utils.test.tsx
- packages/location-management/src/components/LocationForm/utils.tsx
- packages/location-management/src/components/NewLocationUnit/tests/__snapshots__/index.test.tsx.snap
- packages/location-management/src/lang.ts
Add latitude and longitude fields for Add Edit structures
sync the geometry values across the 3 fields i.e .geometry, latitude and longitude,
How? by using an onValues change handler, one can observe for changes to any fields(in this case geometry, latitude, and longitude) and sync those changes to any other fields using form.setFieldsValue
> Service point lat long

- packages/inventory/src/containers/EditServicePoint/tests/index.test.tsx
- packages/location-management/package.json
- packages/location-management/src/components/EditLocationUnit/index.tsx
- packages/location-management/src/components/EditLocationUnit/tests/index.test.tsx
- packages/location-management/src/components/LocationForm/index.tsx
- packages/location-management/src/components/LocationForm/tests/utils.test.tsx
- packages/location-management/src/components/LocationForm/utils.tsx
- packages/location-management/src/ducks/location-units.ts
- packages/location-management/src/ducks/tests/location-units.test.ts
- packages/product-catalogue/src/components/ListView/index.tsx
- packages/product-catalogue/src/index.css
- Adds a single selector for location units that should work for all filters,
- Repopulate initial values when they change in the props
- initially get the isJurisdiction status from locationUnit otherwise fallback to passed in arg
- add a className to product-catalogue so that css can be scoped to only single component
> Fix is jurisdiction status when editing service point

- app/src/App/utils.tsx
- packages/inventory/src/containers/CreateServicePoint/index.tsx
- packages/inventory/src/containers/CreateServicePoint/tests/index.test.tsx
- packages/inventory/src/containers/EditServicePoint/index.tsx
- packages/inventory/src/containers/EditServicePoint/tests/index.test.tsx
- packages/location-management/src/components/EditLocationUnit/index.tsx
- packages/location-management/src/components/EditLocationUnit/tests/index.test.tsx
- packages/location-management/src/components/LocationForm/index.tsx
- packages/location-management/src/components/LocationForm/tests/index.test.tsx
- packages/location-management/src/components/NewLocationUnit/index.tsx
- packages/location-management/src/components/NewLocationUnit/tests/index.test.tsx
- correct the redirection urls invoked when either after a successful form submission, or a cancel for creating new service points, and editing service points.
- Disable editing parentId when editing service points 
addresses #310
> Service point QA fixes

- packages/inventory/src/components/InventoryItemForm/index.tsx
- packages/inventory/src/components/InventoryItemForm/tests/index.test.tsx
- packages/inventory/src/containers/InventoryAddEdit/index.tsx
- packages/inventory/src/containers/InventoryAddEdit/tests/index.test.tsx
Addresses #460 
Addresses #461 
Resolve bug Serial number field not displaying when editing an attractive item. The field was only displaying if both **Product** and **Delivery date** were changed hence it only worked when adding a new item 
Resolve bug Accountability end date field not being automatically calculated when editing an item. The  field was only being auto-calculated if both **Product** and **Delivery date** fields were changed, hence it only worked when adding a new item
> Resolve bug Serial number field missing when editing an attractive item

- packages/opensrp-plans/src/components/AssignmentModal/index.tsx
- packages/opensrp-plans/src/components/AssignmentModal/tests/index.test.tsx
Add search filter functionality to select component used for teams and locations assignment in missions
close #481
> Add search filter functionality to teamsLocation assign select

- packages/product-catalogue/package.json
- packages/product-catalogue/src/components/ProductForm/index.tsx
- packages/product-catalogue/src/components/ProductForm/tests/fixtures.tsx
- packages/product-catalogue/src/components/ProductForm/tests/index.test.tsx
- packages/product-catalogue/src/lang.ts
- packages/react-utils/src/helpers/dataLoaders.ts
- packages/react-utils/src/helpers/tests/dataLoaders.test.ts
- yarn.lock
Addresses #399 
The endpoint to get the image required authentication. A 302 status code was being returned with a redirection to the login page. This was resolved by adding the token to the request headers when getting the image
> Resolve bug image preview not displaying when editing product

- packages/pkg-config/package.json
- yarn.lock
After publishing `@opensrp/form-config`, the new version was requesting the package to be added in reveal.
This change moves package `@opensrp/form-config`  in `pkg-config` to `dependencies`
> Move @reduxjs/toolkit from peer dependencies to dependencies

- packages/inventory/src/constants.ts
- packages/inventory/src/containers/CreateServicePoint/index.tsx
- packages/inventory/src/containers/CreateServicePoint/tests/index.test.tsx
before:
- the type field is hidden, and has a default value of undefined, when creating the service point fields, undefined value are removed from the payload.
Fix:
- explicitely provide the default value of the `type` field when creating Service points, this way it will not be undefined, when creating the payload,
addresses https://github.com/OpenSRP/opensrp-client-eusm/issues/60
> Specify geojson type field value when creating service points

- packages/opensrp-plans/src/components/PlanInfo/index.tsx
> plan title style fix

- packages/keycloak-user-management/src/components/CreateEditUser/tests/index.test.tsx
failure reason:
- the order of mocked responses went out of sync, for some reason!.
- Corrected the order, added an assertion that would fail, if such a situation happened again.
> Correct order of mocked responses

- packages/opensrp-plans/src/components/ActivateMission/index.tsx
- packages/opensrp-plans/src/components/ActivateMission/tests/index.test.tsx
- packages/opensrp-plans/src/lang.ts
- packages/plan-form/src/Form/componentsUtils/status.tsx
- packages/plan-form/src/Form/componentsUtils/tests/status.test.tsx
- packages/plan-form/src/Form/index.tsx
- packages/plan-form/src/lang.ts
close #485 
- problem : possible to activate mission that have no assigned locations
Added constraint in 2 places:
- plan-form
- mission assignments: activate mission
> Active plan only with areas

- app/src/App/App.tsx
- app/src/App/tests/App.test.tsx
addresses #531 
We don't need to have the logout component as a private component since private component enforces the use of roles which we really don't need when logging out a user.
> 531 fix logout redirecting to unauthorized page

- packages/plan-form/src/Form/tests/__snapshots__/index.test.tsx.snap
- packages/plan-form/src/Form/tests/index.test.tsx
- packages/plan-form/src/helpers/utils.tsx
- packages/plan-form/src/lang.ts
close #533 
- Adds validation rule that disallows creating plan(mission) names that contain slashes
> Disallow forward slash in mission name

- packages/opensrp-plans/package.json
- packages/opensrp-plans/src/components/MissionData/index.tsx
- packages/opensrp-plans/src/components/MissionData/tests/index.test.tsx
- packages/opensrp-plans/src/constants.ts
- packages/opensrp-plans/src/helpers/dataLoaders.ts
- packages/opensrp-plans/src/helpers/utils.tsx
- packages/opensrp-server-service/src/serviceClass.ts
part of #512 
resolves this comment: https://github.com/OpenSRP/web/issues/512#issuecomment-788022173
we were using the wrong api call to fetch mission indicators for the number of flagged problems
> Fix flag problem mission indicators api call

- app/src/App/tests/App.test.tsx
- app/src/containers/ConnectedSidebar/tests/__snapshots__/index.test.tsx.snap
- packages/product-catalogue/src/components/CreateProduct/tests/__snapshots__/index.test.tsx.snap
- packages/product-catalogue/src/components/EditProduct/tests/__snapshots__/index.test.tsx.snap
- packages/product-catalogue/src/constants.ts
The create view url overlaps with the list view url, redirections to the create product view are intepreted as redirections to the list product view page.
expect a wholesome solution in #395
> Fix Routes regression

- packages/location-management/src/components/LocationUnitList/index.tsx
- packages/location-management/src/components/LocationUnitList/tests/index.test.tsx
Fixes #566 
There's no way to unit test this behaviour
> fix eternal spinner bug when re-visiting the location unit list page

- packages/react-utils/src/helpers/componentUtils.tsx
- packages/react-utils/src/helpers/tests/componentUtils.test.tsx
This PR addresses #560 
Issue: 
- Private route was checking only user is authorised or not by getting values from store.
- On reloading the page, store gets updated and get back to its default state,
Fix:
- Added authenticated check, if user is authenticated then check authorisation else redirect to Login.
> Reloading page redirects to unauthorised page

- packages/location-management/src/components/LocationForm/CustomSelect/index.tsx
- packages/location-management/src/components/LocationForm/index.tsx
- packages/location-management/src/components/LocationForm/tests/fixtures.ts
- packages/location-management/src/components/LocationForm/tests/index.test.tsx
- packages/location-management/src/components/LocationForm/utils.ts
Add prop that defines how to compute full object after user selects option in a select dropdown. such a select action only gives us an id or a an array of ids, however we might be more interested in other props of the selected data obj, this prop customizes how we can compute the full obj from the the ids we get after user does a selection
This is in the location select dropdown
the problem is as described here: https://github.com/OpenSRP/web/issues/595#issuecomment-820949824
Other changes: Rename utils.tsx to utils.ts
Fix #595
> Fix Duplicate LocationTags failing Editing location Units

- .github/workflows/docker-publish.yml
- Dockerfile
Things noticed during docker image build.
- The build and push for amd64 images work well with no issues, on the other hand arm64 images need a change on the Dockerfile to include `--network-timeout` since there seems to be a network connection issues on arm64 arch refer to https://github.com/nodejs/docker-node/issues/1335
- Build times for amd64 ~ 14min but for amd64 and arm64 it takes ~ 1hr refer to https://github.com/opensrp/web/actions/workflows/docker-publish.yml.
> Add docker build push ci

- packages/keycloak-user-management/src/components/forms/UserForm/index.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/tests/index.test.tsx
_Right Now pressing cancel button on user edit takes to url with user/list which was removed by pr Sidemenu Refractor_
_Ideally the back button should take to history.goback rather than some specific url_
Closes #620
> cancel on user edit should take to users url not user/list url

- packages/card-support/package.json
- packages/error-boundary-fallback/package.json
- packages/form-config-antd/package.json
- packages/form-config-core/package.json
- packages/form-config/package.json
- packages/inventory/package.json
- packages/keycloak-service/package.json
- packages/keycloak-user-management/package.json
- packages/location-management/package.json
- packages/opensrp-notifications/package.json
- packages/opensrp-plans/package.json
- packages/opensrp-reducer-factory/package.json
- packages/opensrp-server-service/package.json
- packages/opensrp-store/package.json
- packages/pkg-config/package.json
- packages/plan-form-core/package.json
- packages/plan-form/package.json
- packages/product-catalogue/package.json
- packages/react-utils/package.json
- packages/team-assignment/package.json
- packages/team-management/package.json
- packages/template/package.json
- remove separate scripts for windows this will allow windows user to use default transpile script rather than overriding it
> Remove Windows scripts

- packages/team-management/package.json
- packages/team-management/src/components/TeamsAddEdit/Form.tsx
- packages/team-management/src/components/TeamsAddEdit/index.tsx
- packages/team-management/src/components/TeamsAddEdit/tests/Form.test.tsx
- packages/team-management/src/components/TeamsAddEdit/tests/fixtures.ts
- packages/team-management/src/components/TeamsAddEdit/tests/index.test.tsx
- packages/team-management/src/components/TeamsView/index.tsx
- Fix team members list to display practitioner name instead of UUID on team edit page
closes #659
> 659 fix team members on edit bug

- packages/team-management/src/components/TeamsAddEdit/Form.tsx
- packages/team-management/src/components/TeamsAddEdit/index.tsx
- packages/team-management/src/components/TeamsAddEdit/tests/Form.test.tsx
- packages/team-management/src/components/TeamsAddEdit/tests/__snapshots__/Form.test.tsx.snap
- packages/team-management/src/components/TeamsAddEdit/tests/index.test.tsx
default team members to names instead of identifiers.
The practitioners belonging to a team default's to a list of all practitioners identifiers who belong to that team. This PR changes that to a list of all practitioners names belonging to the team.
> use default practitioner name instead of identifier

- packages/react-utils/src/helpers/componentUtils.tsx
- packages/react-utils/src/helpers/tests/componentUtils.test.tsx
- fixes #715 
- add a unique key prop to routes that render the same component on url param change. This makes them update internal state on every render. See discussion [here](https://github.com/opensrp/web/pull/718)
> Unique key prop for same component

- packages/keycloak-user-management/src/components/UserList/TableActions/index.tsx
- packages/keycloak-user-management/src/components/UserList/TableActions/tests/utils.test.tsx
- packages/keycloak-user-management/src/components/UserList/TableActions/utils.tsx
- packages/keycloak-user-management/src/components/UserList/index.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/utils.tsx
- packages/keycloak-user-management/src/constants.ts
- packages/keycloak-user-management/src/lang.ts
- closes #694 
- add deactivating a practitioner and un-assigning them from teams after the tied user is deleted
> 694 disable and un-assign practitioner on user delete

- packages/keycloak-user-management/src/components/forms/UserForm/tests/index.test.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/tests/utils.test.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/utils.tsx
Revert: Get keycloak user id from post request reponse
Make fix to regression after wrong assumption that you could generate a uuid when creating a keycloakUser, 
closes :  #775
> Revert: Get keycloak user id from post request reponse

- packages/keycloak-user-management/src/components/forms/UserForm/tests/utils.test.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/utils.tsx
- closes #800 
- push history to `/keycloak-id` instead of `/practitioner-id` (used to point to keycloak id when editing user)
- update tests
> push history to /keycloak-id instead of /practitioner-id

- packages/react-utils/package.json
- packages/react-utils/src/helpers/dataLoaders.ts
- packages/react-utils/src/helpers/tests/dataLoaders.test.ts
- packages/react-utils/src/helpers/tests/fixtures.ts
- packages/react-utils/src/helpers/utils.tsx
- yarn.lock
This Pr adds intellisense in return .. instead of returnging generic resource we can optinally be specific and return the type we really want
like 
```
const serve = new FHIRServiceClass<Organization>(fhirbaseURL, 'Organization');
const resp: Organization = await serve.create(payload); <- update will return Organization type
```
> Add return type in Fhirservice

- app/src/App/tests/App.test.tsx
- packages/card-support/src/components/DownloadClientData/index.tsx
- packages/card-support/src/components/DownloadClientData/tests/__snapshots__/index.test.tsx.snap
- packages/card-support/src/components/DownloadClientData/tests/fixtures.ts
- packages/card-support/src/components/DownloadClientData/tests/index.test.tsx
- packages/card-support/src/constants.ts
- packages/card-support/src/lang.ts
- setupTests.js
- closes #900 
- get location hierarchy of logged in user from security authenticate endpoint ( location id of location assigned to the team which the logged in user is assigned to -> generate location hierarchy from the location id) 
- replaces https://github.com/opensrp/web/pull/907 - because better approach (fewer api calls)
> fix card support location hierarchy

- packages/card-support/src/components/DownloadClientData/index.tsx
- packages/card-support/src/components/DownloadClientData/tests/__snapshots__/index.test.tsx.snap
- packages/card-support/src/components/DownloadClientData/tests/fixtures.ts
- packages/card-support/src/components/DownloadClientData/tests/index.test.tsx
- packages/card-support/src/components/DownloadClientData/tests/utils.test.tsx
- packages/card-support/src/components/DownloadClientData/utils.tsx
- closes #900 
- fetch all nested location ids for the selected location in the hierarchy tree; to be included in fetching download data
> include nested location ids in client search

- packages/fhir-location-management/package.json
- packages/fhir-location-management/src/components/AddEditLocationUnit/index.tsx
- packages/fhir-location-management/src/components/LocationForm/index.tsx
- packages/fhir-location-management/src/components/LocationForm/tests/index.test.tsx
- packages/fhir-location-management/src/components/LocationForm/utils.ts
- packages/fhir-location-management/src/components/LocationUnitList/index.tsx
- packages/fhir-location-management/src/components/LocationUnitList/tests/index.test.tsx
- yarn.lock
Fix success/Cancel url prop in fhir location form
close #948
> Fix success/Cancel url prop in fhir location form

- app/package.json
- remove git add from lint staged - no longer needed on version 10 upwards https://github.com/okonet/lint-staged/issues/775#issuecomment-577106594
- we are on version 12> https://github.com/opensrp/web/blob/4022c9076c461f5bbff8883e24ca19cc6961850a/package.json#L99
> remove git add from lint staged

- app/.env.sample
- app/.env.test
- docs/how-to-use-docker-image.md
- closes https://github.com/opensrp/web/issues/1030
- disable inlining images and scripts in the react build - in line with csp policy recommendations
> disable in lining images and scripts in react build

- packages/fhir-keycloak-user-management/src/components/UserList/ViewDetails/index.tsx
- packages/fhir-team-management/src/components/AddEditOrganization/Form.tsx
- packages/fhir-team-management/src/components/AddEditOrganization/tests/Form.test.tsx
- packages/fhir-team-management/src/components/AddEditOrganization/tests/__snapshots__/Form.test.tsx.snap
- packages/fhir-team-management/src/components/AddEditOrganization/utils.ts
- packages/fhir-team-management/src/components/OrganizationList/ListView/index.tsx
- packages/fhir-team-management/src/components/OrganizationList/ListView/tests/__snapshots__/index.test.tsx.snap
- packages/fhir-team-management/src/components/OrganizationList/ListView/tests/fixtures.tsx
- packages/fhir-team-management/src/components/OrganizationList/ListView/tests/index.test.tsx
- packages/fhir-team-management/src/components/OrganizationList/ViewDetails/index.tsx
- packages/react-utils/src/components/KeyValuePairs/index.tsx
closes #1080 
- remove type column in organization list
- Show practitioners assigned to an organization in the organization detail view
- hide type field in org form
- Reorder org form active radio groups and default to true when creating a new organization
> Fhir team management ui updates.

- packages/fhir-group-management/src/components/CommodityAddEdit/Form.tsx
- packages/fhir-group-management/src/components/CommodityAddEdit/tests/Form.test.tsx
- packages/fhir-group-management/src/components/CommodityAddEdit/tests/__snapshots__/Form.test.tsx.snap
- packages/fhir-group-management/src/components/CommodityAddEdit/utils.ts
closes #1084 
- Reorders radio buttons for active, Select active by default for new groups
- Show id and identifier fields
> Update commodity create/edit form view

- packages/fhir-team-management/src/components/AddEditOrganization/index.tsx
- packages/fhir-team-management/src/components/AddEditOrganization/tests/index.test.tsx
Load organization for edit only after assigned practtioners are fully loaded
- close #1158
> Load organization for edit only after assigned practtioners are fully loaded

- .yarnrc
- packages/opensrp-plans/src/containers/NewPlan/tests/index.test.tsx
Not sure why yet, but using react testing library act fixed the issue in these tests.
> Inspect long running test in opensrp-plans

- app/src/App/App.tsx
- packages/fhir-care-team/src/components/ListView/index.tsx
- packages/fhir-care-team/src/components/ListView/tests/__snapshots__/index-rtl.test.tsx.snap
- packages/fhir-care-team/src/components/ListView/tests/index-rtl.test.tsx
- packages/fhir-care-team/src/components/ViewDetails/index.tsx
- packages/fhir-care-team/src/components/ViewDetails/tests/__snapshots__/index.test.tsx.snap
- packages/fhir-care-team/src/components/ViewDetails/tests/index.test.tsx
- packages/fhir-team-management/src/components/OrganizationList/ViewDetails/index.tsx
- packages/i18n/locales/eusm/fhir-care-team/en.json
- packages/i18n/locales/eusm/fhir-care-team/fr.json
- packages/i18n/locales/eusm/fhir-team-management/en.json
- packages/i18n/locales/eusm/fhir-team-management/fr.json
- packages/react-utils/src/hooks/tests/useSearchParams.test.tsx
- packages/react-utils/src/hooks/useSearchParams.ts
Checks if weve appended a url before appending another.
closes #1216
> Fix useSearchParams to replace the url instead of appending to the existing

- packages/fhir-location-management/src/components/LocationForm/index.tsx
- packages/fhir-location-management/src/components/LocationForm/tests/__snapshots__/index.test.tsx.snap
- packages/fhir-location-management/src/components/LocationForm/tests/index.test.tsx
Fixes the error caused by accidentally removing the name property from the field input.
closes  #1224
> fix broken ci run

- packages/keycloak-user-management/src/components/CreateEditUser/tests/__snapshots__/index.test.tsx.snap
- packages/keycloak-user-management/src/components/forms/UserForm/index.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/utils.tsx
- packages/keycloak-user-management/src/ducks/user.ts
The application id is returned as a string array, so this changes the user attribute to a string array then access the value.
closes #1229
> Pre-poulate application id field

- packages/fhir-keycloak-user-management/src/components/UserList/ListView/index.tsx
- packages/fhir-keycloak-user-management/src/components/UserList/ListView/tableColumns.tsx
- packages/fhir-keycloak-user-management/src/components/UserList/ListView/tests/index.test.tsx
closes #1246 
Add credentials option in dropdown options in user management that prompts the user for a new password and sets it as the new password.
> Enable password reset for practitioners

- packages/fhir-keycloak-user-management/src/components/CreateEditUser/index.tsx
- packages/fhir-keycloak-user-management/src/components/CreateEditUser/tests/fixtures.ts
- packages/fhir-keycloak-user-management/src/components/CreateEditUser/tests/index.test.tsx
- packages/fhir-keycloak-user-management/src/components/CreateEditUser/tests/new-user.test.tsx
- packages/keycloak-user-management/src/components/UserList/TableActions/index.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/tests/utils.test.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/utils.tsx
close #1254 
Fix url used to redirect to the credentials view.
- Add username to urls that should redirect to credentials view
- Add a create user test that also checks that final redirection to credentials view is valid
> Fix credentials redirect url

- packages/fhir-team-management/src/components/AddEditOrganization/index.tsx
- packages/fhir-team-management/src/components/AddEditOrganization/tests/index.test.tsx
close #1255
Add active filter when fetching for practitioners to assign to organizations, and when fetching practitionerRoles.
Caveat, to prevent a flash of content we also now enforce a loader till data is refetched.
> Filter only active practitioners to be available for assigment

- packages/fhir-location-management/src/components/LocationUnitList/index.tsx
- packages/fhir-location-management/src/helpers/flat-to-nested.ts
- packages/fhir-location-management/src/helpers/tests/utils.test.ts
- packages/fhir-location-management/src/helpers/utils.ts
close #1268 
fixes problem where partOf field reference value was malformed. It should be `[resource -type]/[resource-id]` but was `resource-id`
> FIx Location creation

- packages/keycloak-user-management/src/components/CreateEditUserGroup/Form.tsx
- packages/keycloak-user-management/src/components/CreateEditUserGroup/index.tsx
- packages/keycloak-user-management/src/components/CreateEditUserGroup/tests/__snapshots__/index.test.tsx.snap
- packages/keycloak-user-management/src/components/CreateEditUserGroup/tests/index.test.tsx
- packages/keycloak-user-management/src/components/UserGroupDetailView/index.tsx
- packages/keycloak-user-management/src/components/UserGroupDetailView/tests/__snapshots__/index.test.tsx.snap
- packages/keycloak-user-management/src/components/UserGroupDetailView/tests/index.test.tsx
- packages/keycloak-user-management/src/components/UserGroupsList/index.tsx
- packages/keycloak-user-management/src/components/UserGroupsList/tests/fixtures.ts
Move effective roles out of forms to a keycloak's group details view.
close #1263
> Refactor keycloak groups view

- packages/react-utils/src/helpers/componentUtils.tsx
- packages/react-utils/src/helpers/tests/componentUtils.test.tsx
close #1278 
Nest Rbac checker within ConnectedPrivateRoute so that we can check the AuthN state before AuthZ.
> Fix missing session state on browser reload.

- packages/fhir-location-management/src/components/LocationUnitList/index.tsx
- packages/fhir-location-management/src/components/LocationUnitList/tests/__snapshots__/index.test.tsx.snap
- packages/fhir-location-management/src/components/LocationUnitList/tests/index.test.tsx
On the locations page, selecting a node and then clicking the add location unit, should default to using that location as the intended parent node in the add edit location view. There seems to have been a regression where this was no longer the case in recent releases. 
This pr fixes this behavior and correctly identifies the selected node as the default parent node in the location form.
> Fix regression where selected parent node is not passed to addEdit location form

- packages/fhir-location-management/src/components/LocationUnitList/LocationUnitList.css
- packages/location-management/src/components/LocationUnitGroupList/LocationUnitGroupList.css
- packages/location-management/src/components/LocationUnitList/LocationUnitList.css
- packages/plan-form/src/Form/index.tsx
- packages/plan-form/src/Form/tests/index.test.tsx
- packages/server-settings/src/components/ServerSettingsView/ServerSettingsView.css
- packages/team-management/src/components/TeamsView/TeamsView.css
- close #1290 . 
Disable dates in the past. This means 
- start date can only be current date or a future date.
- end date can only be start date or future date.
- Removed table stripping styling.
> Fix Date range picker on the plan form

- packages/react-utils/src/helpers/dataLoaders.ts
- packages/react-utils/src/helpers/tests/dataLoaders.test.ts
closes #1301 , closes #1260, closes #1295 
Adds `cache-control: no-cache` header to `GET` requests when using fhir service. https://smilecdr.com/docs/fhir_storage_relational/performance_and_caching.html#controlling-the-query-cache-client
**Checklist**
> Disable caching when making get requests to the fhir server.

- packages/fhir-group-management/src/components/CommodityAddEdit/Default/tests/index.test.tsx
- packages/fhir-group-management/src/components/CommodityAddEdit/Default/tests/test-utils.ts
- packages/fhir-group-management/src/components/CommodityAddEdit/Eusm/tests/__snapshots__/index.test.tsx.snap
- packages/fhir-group-management/src/components/CommodityAddEdit/Eusm/tests/index.test.tsx
- packages/fhir-group-management/src/components/LocationInventory/form.tsx
- packages/fhir-group-management/src/components/LocationInventory/tests/fixtures.ts
- packages/fhir-group-management/src/components/LocationInventory/tests/form.test.tsx
- packages/fhir-group-management/src/components/LocationInventory/utils.tsx
**closes #**
- Fixes valueSet id for donor field in location inventory form
- A few tweaks to types to a few input form fields.
- Updates tests.
**Checklist**
> Fix value set ids

- packages/fhir-location-management/src/components/ViewDetails/DetailsTabs/Inventory.tsx
- packages/fhir-location-management/src/components/ViewDetails/DetailsTabs/tests/detailsTabs.test.tsx
**closes #1367**
- Update inventory edit link to include inventory id instead of product id
**Checklist**
> Update inventory edit link

- packages/fhir-care-team/src/components/ViewDetails/tests/__snapshots__/index.test.tsx.snap
- packages/fhir-care-team/src/components/ViewDetails/tests/index.test.tsx
- packages/fhir-group-management/src/components/CommodityList/Default/List.tsx
- packages/fhir-group-management/src/components/CommodityList/Default/tests/__snapshots__/list.test.tsx.snap
- packages/fhir-group-management/src/components/CommodityList/Default/tests/list.test.tsx
- packages/fhir-group-management/src/components/CommodityList/Eusm/ViewDetails.tsx
- packages/fhir-group-management/src/components/CommodityList/Eusm/tests/__snapshots__/list.test.tsx.snap
- packages/fhir-group-management/src/components/CommodityList/Eusm/tests/list.test.tsx
- packages/fhir-group-management/src/components/CommodityList/Eusm/tests/viewDetails.test.tsx
- packages/fhir-group-management/src/components/GroupList/index.tsx
- packages/fhir-group-management/src/components/GroupList/tests/__snapshots__/index.test.tsx.snap
- packages/fhir-group-management/src/components/GroupList/tests/index.test.tsx
- packages/fhir-healthcare-service/src/components/HealthCareDetail/index.tsx
- packages/fhir-location-management/src/components/ViewDetails/LocationDetails/index.tsx
- packages/fhir-resources/src/Questionnaire/details.tsx
- packages/fhir-team-management/src/components/OrganizationList/ListView/tests/__snapshots__/index.test.tsx.snap
- packages/fhir-team-management/src/components/OrganizationList/ListView/tests/index.test.tsx
- packages/react-utils/src/components/GenericDetailsView/ResourceDetails/index.tsx
- packages/react-utils/src/components/GenericDetailsView/ResourceDetails/tests/index.test.tsx
- packages/react-utils/src/components/GenericDetailsView/index.css
- packages/react-utils/src/components/GenericDetailsView/index.tsx
- packages/react-utils/src/components/KeyValuePairs/index.css
- packages/react-utils/src/components/KeyValuePairs/index.tsx
- packages/react-utils/src/components/KeyValuePairs/tests/index.test.tsx
- packages/react-utils/src/index.tsx
**Part of #1388**
- Creates a generic resource details component
**Checklist**
> Creates a generic resource details component

- packages/fhir-group-management/src/components/LocationInventory/tests/fixtures.ts
- packages/fhir-group-management/src/components/LocationInventory/tests/form.test.tsx
- packages/fhir-group-management/src/components/LocationInventory/utils.tsx
- packages/fhir-helpers/src/constants/codeSystems.ts
- packages/fhir-location-management/src/components/ViewDetails/DetailsTabs/Inventory.tsx
- packages/fhir-location-management/src/components/ViewDetails/DetailsTabs/tests/detailsTabs.test.tsx
**closes #1384 **
updated the post inventory util function to only create a new location inventory list resource when editing an existing inventory,  not to do so when adding a new inventory to a location that has previous assignments .
Update inventory view details section to see all inventories attached to a location even if sharing products
**Checklist**
> Fix duplicate location inventory when adding an inventory

- packages/fhir-group-management/src/components/CommodityAddEdit/Eusm/tests/index.test.tsx
- packages/fhir-group-management/src/components/ProductForm/index.tsx
**closes #1401**
Hide the upload button when an uploaded item already exists. Change the ux so that its clearer one can only upload a single item at a time.
> Hide upload button when a file has already been uploaded

- packages/react-utils/src/helpers/dataLoaders.ts
- packages/react-utils/src/helpers/tests/dataLoaders.test.ts
- setupTests.js
**closes #1424**
- Change casing for header keys so that they correctly override the default content-type added by the fhirclient library
-
> Refactor content-type header casing to correct override

- packages/fhir-location-management/src/components/AllLocationListFlat/core.tsx
- packages/fhir-location-management/src/components/AllLocationListFlat/utils.tsx
- packages/fhir-location-management/src/components/ViewDetails/DetailsTabs/ChildLocations.tsx
- packages/fhir-location-management/src/components/ViewDetails/DetailsTabs/tests/detailsTabs.test.tsx
**closes #1385 **
- Add table actions to edit and view details of locations inside of location view details view
**Checklist**
> Add table actions to location view details child locations tab table

- packages/fhir-helpers/src/constants/codeSystems.ts
- packages/fhir-helpers/src/utils/tests/utils.test.ts
- packages/fhir-location-management/src/components/LocationForm/CustomTreeSelect/index.tsx
- packages/fhir-location-management/src/components/LocationForm/tests/fixtures.ts
- packages/fhir-location-management/src/components/LocationForm/tests/utils.test.ts
- packages/fhir-location-management/src/components/RootLocationWizard/tests/fixtures.ts
- packages/fhir-location-management/src/components/RootLocationWizard/tests/index.test.tsx
- packages/fhir-location-management/src/components/ViewDetails/DetailsTabs/tests/detailsTabs.test.tsx
- packages/fhir-location-management/src/components/ViewDetails/DetailsTabs/tests/fixtures.ts
- packages/fhir-location-management/src/components/ViewDetails/tests/fixtures.ts
- packages/keycloak-user-management/src/components/CreateEditUserGroup/tests/__snapshots__/index.test.tsx.snap
closes #1444 
Update system url that we expect for admin level coding
Remove tree as a dependency array for re-render can be quite huge
- a few other small bug fixes 
**Checklist**
> 1444 location admin fix

- packages/fhir-group-management/src/components/LocationInventory/form.tsx
- packages/fhir-group-management/src/components/LocationInventory/index.tsx
- packages/fhir-group-management/src/components/LocationInventory/tests/form.test.tsx
- packages/fhir-group-management/src/components/LocationInventory/tests/index.test.tsx
- packages/fhir-group-management/src/components/LocationInventory/utils.tsx
**closes #1450**
- make po field optional
- Hide serial number field by default
**Checklist**
> inventory form updates

- packages/fhir-group-management/src/components/ProductForm/index.tsx
**closes #1476**
Rplace refecthQuery with proper query invalidation to prevent scheduling of unncessary malformed requests.
> Fix query cache invalidation

- packages/fhir-group-management/src/components/LocationInventory/form.tsx
- packages/fhir-group-management/src/components/LocationInventory/tests/form.test.tsx
- packages/react-utils/src/components/AsyncSelect/ClientSideActionsSelect/index.tsx
- packages/react-utils/src/components/AsyncSelect/ClientSideActionsSelect/tests/index.test.tsx
- packages/react-utils/src/components/AsyncSelect/PaginatedAsyncSelect/index.tsx
- packages/react-utils/src/components/AsyncSelect/PaginatedAsyncSelect/tests/fixtures.ts
- packages/react-utils/src/components/AsyncSelect/PaginatedAsyncSelect/tests/index.test.tsx
- packages/react-utils/src/components/AsyncSelect/index.tsx
- packages/react-utils/src/components/AsyncSelect/utils.ts
**closes #1477**
- Add a select component that loads all data for a particular resource
- Fixed a pagination bug with the paginationAsyncSelect component
**Checklist**
> Inventory product select update

- .github/ISSUE_TEMPLATE/opensrp-1-web-support.yml
- .github/ISSUE_TEMPLATE/opensrp-web-bug-report.yml
- .github/ISSUE_TEMPLATE/opensrp-web-new-feature-request.yml
> 📝 Update the ticket templates

- packages/fhir-keycloak-user-management/src/components/CreateEditUser/index.tsx
- packages/fhir-keycloak-user-management/src/components/CreateEditUser/tests/extra-fields-user.test.tsx
- packages/fhir-keycloak-user-management/src/components/CreateEditUser/tests/fixtures.ts
- packages/fhir-keycloak-user-management/src/components/CreateEditUser/tests/index.test.tsx
- packages/fhir-keycloak-user-management/src/components/CreateEditUser/tests/new-user.test.tsx
- packages/keycloak-user-management/src/components/CreateEditUser/index.tsx
- packages/keycloak-user-management/src/components/CreateEditUser/tests/__snapshots__/index.test.tsx.snap
- packages/keycloak-user-management/src/components/CreateEditUser/tests/index.test.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/index.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/tests/__snapshots__/index.test.tsx.snap
- packages/keycloak-user-management/src/components/forms/UserForm/tests/index.test.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/tests/index.unmocked.test.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/types.ts
- packages/keycloak-user-management/src/components/forms/UserForm/utils.tsx
- packages/keycloak-user-management/src/constants.ts
- packages/keycloak-user-management/src/index.tsx
- **closes #1489**
Refactor how form fields are configured to show up
Remove surplus and duplicate contact form field.
**Checklist**
> Refactor user management form fields and corresponding props config

- app/src/App/fhir-apps.tsx
- packages/fhir-flag/src/components/BaseComponent/index.tsx
- packages/fhir-flag/src/components/CloseFlagForm/index.tsx
- packages/fhir-import/src/containers/StartImportView/form.tsx
- **closes #1470**
- closes #1452
- Add permissions to bulk upload and fhir import module
**Checklist**
> Permission fhir import and bulk upload module

- packages/fhir-group-management/package.json
- packages/fhir-group-management/src/components/CommodityAddEdit/Eusm/index.tsx
- packages/fhir-group-management/src/components/CommodityAddEdit/Eusm/tests/fixtures.ts
- packages/fhir-group-management/src/components/CommodityAddEdit/Eusm/tests/index.test.tsx
- packages/fhir-group-management/src/components/CommodityAddEdit/Eusm/utils.ts
- packages/fhir-group-management/src/components/ProductForm/index.tsx
- packages/fhir-group-management/src/components/ProductForm/utils.tsx
- yarn.lock
- **closes #1483**
- compress image before upload
- removing or updating the image upload is now reflected as an update to the existing binary resource.
**Checklist**
> Compress image during image upload for product creation

- app/src/App/fhir-apps.tsx
- app/src/App/tests/App.test.tsx
- app/src/configs/dispatchConfig.ts
- app/src/containers/ConnectedSidebar/tests/__snapshots__/index.test.tsx.snap
- app/src/containers/pages/Home/tests/Home.test.tsx
- app/src/containers/pages/Home/tests/__snapshots__/Home.test.tsx.snap
- app/src/routes/index.tsx
- app/src/routes/tests/index.test.tsx
- packages/fhir-flag/src/components/CloseFlagForm/index.tsx
- packages/fhir-flag/src/components/CloseFlagForm/tests/index.test.tsx
- packages/fhir-flag/src/components/LocationFlag/tests/index.test.tsx
- packages/fhir-flag/src/components/ProductFlag/tests/index.test.tsx
- packages/fhir-import/src/containers/ImportDetailView/index.tsx
- packages/fhir-import/src/containers/ImportListView/index.tsx
- packages/fhir-import/src/containers/ImportListView/tests/__snapshots__/index.test.tsx.snap
- packages/pkg-config/src/configStore/index.ts
- packages/pkg-config/src/constants.ts
- packages/pkg-config/src/index.tsx
- packages/rbac/src/adapters/keycloakAdapter.ts
- packages/rbac/src/constants.ts
- packages/rbac/src/helpers/utils.ts
- packages/rbac/src/roleDefinition/index.ts
- packages/react-utils/src/helpers/test-utils.tsx
> Role definition update

- packages/fhir-location-management/src/components/ViewDetails/DetailsTabs/Inventory.tsx
- **closes #1474**
- Remove intermediate date formating that resulted in an error when applying filter to tell whether inventory is active or not.
**Checklist**
> Fix filter for inventory activeness due to accountability end date

- packages/fhir-helpers/src/constants/codeSystems.ts
- packages/fhir-helpers/src/constants/resourceTypes.ts
- packages/fhir-keycloak-user-management/src/components/CreateEditUser/tests/extra-fields-user.test.tsx
- packages/fhir-keycloak-user-management/src/components/CreateEditUser/tests/index.test.tsx
- packages/fhir-keycloak-user-management/src/components/CreateEditUser/tests/new-user.test.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/index.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/tests/index.unmocked.test.tsx
- packages/keycloak-user-management/src/components/forms/UserForm/utils.tsx
- packages/keycloak-user-management/src/constants.ts
- packages/react-utils/src/components/AsyncSelect/ClientSideActionsSelect/index.tsx
- packages/react-utils/src/components/AsyncSelect/PaginatedAsyncSelect/index.tsx
- **closes #1503**
- related: #1380
For appId field in the user management form:
- replace paginatedAsyncSelect with a local searchable select widget since the filtering is bit involved and not exactly supported by the api. 
- We display the `title`, and `identifier` fields in the dropdown. 
- The `identifier` field is not predictivily-searchable on the API using the `:contains` qualifier. The new select widget does the filtering client side.
- Updated the filters used to query for composition resources that act as the dropdown options in the select widget above.
other changes:
- update paginatedAsyncSelect to render correct empty response when the component is loading. It was previously erroneously showing the number 0
> Update request parameters for dropdown for appId field in user creation form.

- packages/fhir-keycloak-user-management/src/components/UserList/ListView/tableColumns.tsx
- packages/fhir-keycloak-user-management/src/components/UserList/ListView/tests/index.test.tsx
- packages/keycloak-user-management/src/components/Credentials/index.tsx
- packages/keycloak-user-management/src/components/Credentials/passwordStrengthMeter.tsx
- packages/keycloak-user-management/src/components/Credentials/tests/__snapshots__/index.test.tsx.snap
- packages/keycloak-user-management/src/components/Credentials/tests/passwordStrengthMeter.test.tsx
- packages/keycloak-user-management/src/components/UserList/TableActions/index.tsx
- packages/keycloak-user-management/src/components/UserList/TableActions/tests/__snapshots__/index.test.tsx.snap
- **closes #1524**
- Rewrite some strings around the Credentials view in the user Management package. This makes it clearer what actions can be done on those views.
- Add a password strength meter to the password input
**Checklist**
> Update credential view strings; Add password meter strength
